### ISSUE TITLE
a-o.ninja - bug

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#100]
### Website with example

This rule '/^((?!(^https?):\/\/(vidfile\.net|(www\.)?youtube\.com|openload\.co|docs\.google\.com|video\.sibnet\.ru|oload\.stream|streamango\.com|vidlox\.tv|(www\.)?rapidvideo\.com|tune\.pk|(www\.)?dailymotion\.com|estream\.to)\/).)*$/$subdocument,domain=a-o.ninja|centrum-dramy.pl|love-drama.pl|vidfile.net' block VK Player.

link for testing ==> https://a-o.ninja/anime/tailenders/1

### Screenshot

https://user-images.githubusercontent.com/5884000/35067520-75dca76a-fbd4-11e7-8f7e-1c5952e016df.png

**Comment by MajkiIT** [comment]
The same rule block Vidlox player 
test link == > https://a-o.ninja/anime/megalo-box/2

**Comment by hoshsadiq** [comment]
@MajkiIT would be good if in the future you can open a new ticket and reference it. I opened the comment at work with the intention of fixing it when I get home, but completely forgot! Anyway! Thanks @SMed79

**Comment by MajkiIT** [comment]
This regex  hide frame with radio online . URL to frame "https://staty.portalradiowy.pl/statystyki/generpanel2/staty.php?ip=s1.slotex.pl&port=7196&style=220&time=10&listen=1&color=000000"

Can you exclude it ?

`/^((?!(^https?):\/\/((www\.)?dailymotion\.com|(www\.)?rapidvideo\.com|(www\.)?youtube\.com|alltube\.tv|clipwatching\.com|docs\.google\.com|ebd\.cda\.pl|estream\.to|flashx.tv|flashx.ws|freedisc\.pl|fruitstreams\.com|gamedor\.usermd\.net|hqq\.tv|hqq\.watch|myvi\.ru|nowvideo\.sx|ok\.ru|oload\.stream|oload\.win|openload\.co|reseton\.net|rutube\.ru|sendvid\.com|st\.chatango\.com|stream\.moe|streamango\.com|streamcherry\.com|streamplay\.cc|thevideo\.me|thevideo\.website|tune\.pk|uptostream\.com|video\.sibnet\.ru|vidfile\.net|vidlox\.me|vidlox\.tv|vidoza\.net|vidto\.me|vidzi\.tv|vshare\.eu|vshare\.io|www\.google\.com\/recaptcha|www\.speedvid\.co|www\.speedvid\.net)\/).)*$/$subdocument,domain=123telugu.com|2giga.link|a-o.ninja|alltube.pl|alltube.tv|centrum-dramy.pl|estream.nu|estream.to|estream.xyz|love-drama.pl|netiap.com|szukajka.tv|vidfile.net|vidzi.si|vidzi.tv`

**Comment by smed79** [comment]
@MajkiIT Provide an an example page where `staty.portalradiowy.pl` is blocked.
