### ISSUE TITLE
Sync with Easyprivacy Coin miners.

### ISSUE THREAD

**Issue by ryanbr** [hoshsadiq/adblock-nocoin-list#101]
Coin mining sites;      (NSFW)

`http://www.camuploads.com/ `                                           https://github.com/easylist/easylist/commit/e00d565d943a72b9f2410e1f8903f990df641296

`https://you.tubetitties.com/UV8p-GcvEpU?t=26`                          https://github.com/easylist/easylist/commit/62e6fdad54f3e37863ed018a8301b104bc896eed

`http://mycouchtuner.nu/`                                               https://github.com/easylist/easylist/commit/5b4980e3e7b7d018712539590a726c6b44368995

`https://love-drama.pl/drama/hana-yori-dango/5   `                      https://github.com/easylist/easylist/commit/db3927149087a8c6fe11a2afc9da1d22b67f820d

`http://alltube.tv/filmik/wkrecili-ruda-laske-na-silowni/226`           https://github.com/easylist/easylist/commit/bc6b918d825996e97fd60d0904ffa6cd08f3100e

`https://akvideo.stream/z8fd35fv24oq `                                  https://github.com/easylist/easylist/commit/2840e48e3727e2523e4b2d276b42a5b3bdafee4d

`https://powvideo.net/9ks9ofsu616y`                                     https://github.com/easylist/easylist/commit/bbc485bb72cd6706bf08291291ab3808c1d56973

`https://vidfile.net/v/58741r268s0or`                                   https://github.com/easylist/easylist/commit/58da248fc7218acc655eba09e89ff41b095ab084

`https://lewd.ninja/`                                                   https://github.com/easylist/easylist/commit/cddd48146de74f29bd28379738d5312c206a2260                                                                      https://github.com/easylist/easylist/commit/dd3cc8581666ec52252a021e9c4a15eb84f5bf28

**Comment by mapx-** [comment]
+ `https://vidfile.net/js/kissmyass/hmm.wasm` on `love-drama.pl`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/db39e5681662f493bea41889b78e0bb049eb427e

**Comment by hoshsadiq** [comment]
Added them! Thanks!
