### ISSUE TITLE
alltube.tv - bug

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#102]
### Website with example

http://alltube.tv/mentalista-the-mentalist/the-great-red-dragon/odcinek-7-sezon-6/481 

### Domain causing the CPU spike
This rule `*$third-party,subdocument,domain=alltube.tv `hide all players nad recaptcha. 

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by hoshsadiq** [comment]
Fixed.
