### ISSUE TITLE
fileone.tv

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#104]
### Website with example

http://ekino-tv.pl/movie/show/jej-mroczna-przeszlosc-hd-her-dark-past-2016-napisy/21763

### Domain causing the CPU spike

||flare-analytics.com^

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by SMed79** [comment]
I do not see `flare-analytics.com` !!

Post a screenshot and the full url.

**Comment by mapx-** [comment]
click play smed

**Comment by MajkiIT** [comment]
@mapx- Thanks

**Comment by hoshsadiq** [comment]
Merged
