### ISSUE TITLE
sparechange.io

### ISSUE THREAD

**Issue by ptytb** [hoshsadiq/adblock-nocoin-list#106]
### Website with example

These guys provide mining as a service: https://sparechange.io

### Domain causing the CPU spike

Sites using their service download miner script from the same domain:

https://static.sparechange.io/static/index_wasm.js

### Screenshot

I've saved JS console log sample
[www.stocksmarketnews.com-1516560930342.log](https://github.com/hoshsadiq/adblock-nocoin-list/files/1650086/www.stocksmarketnews.com-1516560930342.log)

**Comment by hoshsadiq** [comment]
Thanks, merged #107
