### ISSUE TITLE
aj-crypto-miner

### ISSUE THREAD

**Issue by GoGoris** [hoshsadiq/adblock-nocoin-list#108]
### Website with example

https://www.gadgetgear.nl/

This is a miner for wordpress, so probably more sites will be affected.

### Domain causing the CPU spike

Local script:
https://www.gadgetgear.nl/wp-content/plugins/aj-crypto-miner/assets/ajcn.wasm?ver=1.0.8

Proposed filter: `*/aj-crypto-miner/*$xmlhttprequest`

### Screenshot
<img width="481" alt="schermafbeelding 2018-01-22 om 20 48 17" src="https://user-images.githubusercontent.com/2930063/35241210-040a1146-ffb6-11e7-845e-62f96c998a49.png">

**Comment by SMed79** [comment]
PR: [109/files#diff-5b21dc408f95a10dada737fbb677d6a9R50](https://github.com/hoshsadiq/adblock-nocoin-list/pull/109/files#diff-5b21dc408f95a10dada737fbb677d6a9R50)

**Comment by hoshsadiq** [comment]
Merged #109

**Comment by GoGoris** [comment]
Great!
