### ISSUE TITLE
centrum-dramy.pl - bug

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#127]
### Website with example

Rule block player

Test link https://centrum-dramy.pl/video/piekielna-gra-2002-lektor-pl/

### Screenshot

![2018-01-31_0805](https://user-images.githubusercontent.com/11302675/35609479-c03660b0-065d-11e8-85f3-d79b967c6651.png)

**Comment by SMed79** [comment]
added `ebd.cda.pl` ([PR#128](https://github.com/hoshsadiq/adblock-nocoin-list/pull/128/files))

for the video ads add these filters https://forums.lanik.us/viewtopic.php?f=62&t=39842

@ryanbr fyi.
