### ISSUE TITLE
Mining code on rintindown.com

### ISSUE THREAD

**Issue by pr0t4zy** [hoshsadiq/adblock-nocoin-list#131]
### Website with example
http://kinokong.cc/32614-smert-stalina-2017-online.html

### Domain causing the CPU spike

rintindown.com

**Comment by SMed79** [comment]
@hoshsadiq I want to submit these changes:
- [nocoin.txt](https://pastebin.com/raw/NUTXdJdj)
- [hosts.txt](https://pastebin.com/raw/cKURhiQG)

Do you approve?

**Comment by hoshsadiq** [comment]
Yeah looks good to me. Curious where you got those?

**Comment by hoshsadiq** [comment]
Never mind. I saw. You wanna make a commit? Otherwise happy to do it.

**Comment by SMed79** [comment]
Done. Thank you.
