### ISSUE TITLE
Obfuscated mining site

### ISSUE THREAD

**Issue by Mioni** [hoshsadiq/adblock-nocoin-list#135]
### Website with example

http://www.clickwith.bid/s/?utm_source=50onred&utm_campaign=50onred-mainstream-ww-winmac_ch-WL&utm_content=monova.to&utm_medium=PATH_335&utm_term=335-okunr&cpv=0.000328

### Screenshot

![untitled](https://user-images.githubusercontent.com/6830783/35770383-d57feac0-08f8-11e8-98ca-aaf90e9909b0.png)

It is obfuscated but would it have some way to block without using noscript extension?

**Comment by SMed79** [comment]
add `||clickwith.bid^`

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/de/ip-address/165.227.91.214/information/
