### ISSUE TITLE
cdn.nablabee

### ISSUE THREAD

**Issue by elvishp2006** [hoshsadiq/adblock-nocoin-list#137]
### Website with example

https://leitor.net/

### Domain causing the CPU spike

wss://wss.nablabee.com

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by SMed79** [comment]
@hoshsadiq add also
```
/crypto-js.min.js
```
e.g `https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js`

**Comment by hoshsadiq** [comment]
Good idea. Added.

**Comment by robinmoisson** [comment]
That's also blocking legitimate use of the [crypto-js](https://github.com/brix/crypto-js) library (from this cdn at least https://cdnjs.com/libraries/crypto-js) which can be used to do crypto in browser.

I'm using it here for example: https://robinmoisson.github.io/staticrypt/

The lib itself is simply a collection of cryptographic algorithms and doesn't do any mining, any way to get more specific in the ban to whitelist it? Thanks !

**Comment by hoshsadiq** [comment]
I won't have a computer to hand right for the next 2 weeks, but will try to fix it ASAP. Meanwhile I'll reopen this so we don't lose track.

**Comment by hoshsadiq** [comment]
#152 fixes this.
