### ISSUE TITLE
browsealoud.com (Miner)

### ISSUE THREAD

**Issue by runboy93** [hoshsadiq/adblock-nocoin-list#145]
https://publicwww.com/websites/browsealoud.com%2Fplus%2Fscripts%2Fba.js/

`//www.browsealoud.com/plus/scripts/ba.js`

**Comment by runboy93** [comment]
https://github.com/easylist/easylist/commit/a5ac72f9fb1c36a38dd1ab08005b2138905fcb0d

**Comment by hoshsadiq** [comment]
I think the miner on browsealoud was coinhive anyway
