### ISSUE TITLE
crypto-js.js probably shouldn't be blocked

### ISSUE THREAD

**Issue by tsimionescu** [hoshsadiq/adblock-nocoin-list#151]
crypto-js.js and crypto-js.min.js are both references to a legitimate, well-known JavaScript cryptography library (used for example to encrypt tokens for implementing secure logins over HTTP): 

https://github.com/brix/crypto-js

It looks like they shouldn't be blocked by default (personally, it's affecting a product I work on which uses this library to implement OpenID Connect).

Update: looks like this may already be tracked as #137 , but leaving this as a little more explicit. Please let me know if you'd prefer to close it.

**Comment by hoshsadiq** [comment]
This has been fixed in #152!
