### ISSUE TITLE
why /authedmine.min.js /authedminer.js are listed on the nocoin.txt?

### ISSUE THREAD

**Issue by kintaro1981** [hoshsadiq/adblock-nocoin-list#154]
Hello,

I saw that /authedmine.min.js and /authedminer.js are listed in nocoin.txt.

Can I ask why?

**Comment by SMed79** [comment]
Hi,
why should not be? Do you know what is the purpose of [NoCoin adblock list](https://github.com/hoshsadiq/adblock-nocoin-list#nocoin-adblock-list)?
