### ISSUE TITLE
1337x

### ISSUE THREAD

**Issue by purevertigo** [hoshsadiq/adblock-nocoin-list#164]
### 1337x

<< Example of pages that are mining >>

### 1337x
![capture](https://user-images.githubusercontent.com/6506461/36942698-83202614-1fcd-11e8-85ba-b337ed1e3547.JPG)

<< The domain that's actually doing the mining >>
<< For example coin-hive, coin-have etc (not the actual page) >>
<< You may leave this empty >>

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by SMed79** [comment]
1337x what ? we can not read your mind.
When creating a new issue, mind the template and provide the necessary infos

**Comment by purevertigo** [comment]
Sorry, I'm going to close the issue as I don't understand how to get all that information. 

thanks.

**Comment by hoshsadiq** [comment]
@purevertigo just  link to the page that's mining is enough, however, I can't see 1337x.to mining when I visit any pages.

![image](https://user-images.githubusercontent.com/600045/36945366-b59d81d2-1fa4-11e8-803c-9a6d6033adf3.png)

**Comment by purevertigo** [comment]
@hoshsadiq sorry, maybe I was wrong. Only when I visited that website did my CPU spike to 100% and the browser froze. When I closed the tab then all OK.
