### ISSUE TITLE
onlinevideoconverter.com

### ISSUE THREAD

**Issue by marto55555** [hoshsadiq/adblock-nocoin-list#165]
### Website with example

The website is mining a cryptocurrency ONLY after successfully converting a video from YouTube, such as:
https://www.onlinevideoconverter.com/success?id=i8f5i8d3f5i8d3e4c2b1

### Domain causing the CPU spike

The domain with the miner seems to be the same as the website.

### Screenshot

![screenshot 2018-03-04 at 11 28 15](https://user-images.githubusercontent.com/15653942/36944263-24355cfe-1fa1-11e8-8bda-51373a2eb61b.png)

Here are the Web Worker threads for mining:
![screenshot 2018-03-04 at 11 35 02](https://user-images.githubusercontent.com/15653942/36944264-2456e086-1fa1-11e8-916c-bdf943196152.png)

**Comment by hoshsadiq** [comment]
#166 fixes this

**Comment by smed79** [comment]
@mapx- The mining script and the anti adblock is removed from onlinevideoconverter.com
see [hoshsadiq/adblock-nocoin-list#250](https://git.io/vh1Nw)
