### ISSUE TITLE
Szukajka.tv exception

### ISSUE THREAD

**Issue by vidoza** [hoshsadiq/adblock-nocoin-list#168]
Is it possible to add exception for szukajka.tv XMLHTTPREQUEST? I mean exactly that request http://szukajka.tv/jsverify.php?op=tag . How I managed to determine, they use it to prevent bots from scan their content. If that request is blocked I can't watch videos :(

**Comment by vidoza** [comment]
Can you add one more expection? Right now JS search form also doesn't works because your list blocks XMLHTTPREQUEST to http://szukajka.tv/szukaj which allows to serach content.

**Comment by SMed79** [comment]
@vidoza Are you the webmaster?
