### ISSUE TITLE
salon.com

### ISSUE THREAD

**Issue by mtcjayne** [hoshsadiq/adblock-nocoin-list#177]
### Website with example

https://www.salon.com/2017/11/11/a-brief-history-of-the-walking-simulator-gamings-most-detested-genre/

See https://www.salon.com/assets/app.js for where they are loading the miner with site key aDIz2u9mp2K17F5SbGVGYItUkoHtYq4Z. They've made it obnoxious to actually find since it's a massive Javascript file on one line. I don't know if it can even be blocked.

**Comment by mtcjayne** [comment]
It appears that blocking that file leaves the site still usable, however since it's so huge I don't know what functionality I'm disabling other than the miner.

**Comment by hoshsadiq** [comment]
@SMed79 i noticed you pushed a commit while I was looking for a fix. I've raised a PR, I'm including the domain you've included too. I'm on a corporate network atm, so it's hard to investigate as it's intermittent. Can you have a look and see if you agree?

**Comment by SMed79** [comment]
> i noticed you pushed a commit while I was looking for a fix

I forgot to submit the pull request :-P

> Can you have a look and see if you agree? PR 178

`cent.spots.im` Is not related to mining.

**Comment by hoshsadiq** [comment]
Cool! In that case I merged yours!
