### ISSUE TITLE
[Info] Reference

### ISSUE THREAD

**Issue by funilrys** [hoshsadiq/adblock-nocoin-list#180]
Hello @hoshsadiq ,

Because I want to be transparent, I just wanted to inform you that we added your hosts file to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/adblock-nocoin-list](https://github.com/Ultimate-Hosts-Blacklist/adblock-nocoin-list).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by hoshsadiq** [comment]
Great! Thanks.
