### ISSUE TITLE
alltube.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#188]
![2018-03-19-prawo ulicy _ the wire - odcinek 1 sezon 1 alltube - filmy i seriale online](https://user-images.githubusercontent.com/5884000/37612138-a2eb1c5a-2ba4-11e8-8490-f430b96f8144.png)
`http://alltube.pl/prawo-ulicy-the-wire/the-target/odcinek-1-sezon-1/6566`

video not work

**Comment by SMed79** [comment]
Dont spam https://github.com/hoshsadiq/adblock-nocoin-list/issues/189 !!

**Comment by KonoromiHimaries** [comment]
@SMed79 i be first
Please, do not denigrate me
