### ISSUE TITLE
vidto cpu usage

### ISSUE THREAD

**Issue by ryanbr** [hoshsadiq/adblock-nocoin-list#200]
### Website with example

`http://vidto.me/jc2qbuqxt6ro.html`

### Domain causing the CPU spike

Trying to debug this one, it uses all my cores. But everything is blocked? Have I missed something or is there is bug?

**Comment by SMed79** [comment]
@ryanbr add `||video.videos.vidto.me^`

**Comment by ryanbr** [comment]
Also applicable on `https://estream.to/4uomw2kfp79q.html`

`https://video.streaming.estream.to/player.js`
