### ISSUE TITLE
coinhive getting through

### ISSUE THREAD

**Issue by hoshsadiq** [hoshsadiq/adblock-nocoin-list#214]
> Hey I'm new to this; my apologies if I don't do this correctly..
> I just love that you are doing this and wanted to share that coinhive is still getting through somehow:
> ![screenshot of malwarebytes](https://user-images.githubusercontent.com/38705756/39215993-9f223610-47df-11e8-89af-b903e9fc1865.png)
\- @dmitriwhy

also, as @SMed79 said, always open a new issue so it can be tracked properly.

Additionally, could you please give an example url?

**Comment by hoshsadiq** [comment]
@dmitriwhy I will close this issue. If the problem persist, comment on this issue and I'll reopen it.

**Comment by dmitriwhy** [comment]
the url that it was coming from was http://www.skymem.info/

**Comment by smed79** [comment]
Should be already blocked if you have an [adblock](https://adblockplus.org/) installed in your browser with [NoCoin list](https://adblockplus.org/subscriptions#type_other) enabled.
