### ISSUE TITLE
a-o.ninja - bug

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#217]
### Website with example

This rule block streamcherry.com and thevideo.me players. You can check on this link ==> https://a-o.ninja/anime/kakuriyo-no-yadomeshi/4

`/^((?!(^https?):\/\/(alltube\.tv|vidfile\.net|(www\.)?youtube\.com|openload\.co|docs\.google\.com|video\.sibnet\.ru|oload\.stream|streamango\.com|vidlox\.tv|(www\.)?rapidvideo\.com|tune\.pk|(www\.)?dailymotion\.com|estream\.to|ebd\.cda\.pl|flashx.tv|flashx.ws|fruitstreams\.com|gamedor\.usermd\.net|hqq\.tv|hqq\.watch|nowvideo\.sx|ok\.ru|rutube\.ru|sendvid\.com|stream\.moe|st\.chatango\.com|uptostream\.com|vidlox\.me|vidoza\.net|vshare\.io|www\.speedvid\.co|www\.speedvid\.net|www\.google\.com\/recaptcha)\/).)*$/$subdocument,domain=123telugu.com|2giga.link|a-o.ninja|alltube.pl|alltube.tv|centrum-dramy.pl|estream.to|love-drama.pl|netiap.com|szukajka.tv|vidfile.net`

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by smed79** [comment]
@MajkiIT Do not post post duplicate #62 #100 #185 #189 to avoid confusion and provide better continuity and tracking to the same issue (a-o.ninja).
