### ISSUE TITLE
i found more sites hope to involved in your list 

### ISSUE THREAD

**Issue by mike1992mamoun** [hoshsadiq/adblock-nocoin-list#22]
as i said i found some Cryptocurrency Mining sites that not involve in your list and all these sites appear when you open straming sites that include openload.co/oload.tv servise 

azvjudwr.info
jroqvbvw.info
jyhfuqoh.info

**Comment by hoshsadiq** [comment]
Thank you, @SMed79 raised a PR and it's been merged.
