### ISSUE TITLE
jqrcdn.download

### ISSUE THREAD

**Issue by dggomes256** [hoshsadiq/adblock-nocoin-list#223]
### Website with example

https://www.caitasupermercados.com.br/

### Domain causing the CPU spike

https://www.jqrcdn.download/
( mining through:
 wss://ws1.webminerpool.com:80/
wss://ws2.webminerpool.com:80/
wss://ws3.webminerpool.com:80 )

### Screenshot

https://imgur.com/a/rl9vbOS

**Comment by hoshsadiq** [comment]
Thanks, fixed.

**Comment by smed79** [comment]
Hmm... most probably a compromised/hacked website.

`webminerpool.com` is altready blocked here https://github.com/hoshsadiq/adblock-nocoin-list/commit/9638568bb7d8b953ea8cd24d24a007685f6f54d8
adding `minexmr.com` has no effect and will not stop mining but only break the site.

@ryanbr @okiehsch fyi.
