### ISSUE TITLE
Please change the Ips you are linking back to 

### ISSUE THREAD

**Issue by TheWatcherofWays** [hoshsadiq/adblock-nocoin-list#226]
All of your ranges are pointing back to 0.0.0.0, this isn't best practices, instead, you would want to send the traffic to 127.0.0.1. While 0.0.0.0 is technically un-routable it can open up other vulnerabilities.

**Comment by smed79** [comment]
> Traditionally most host files use `127.0.0.1`, the loopback address, to establish an IP connection to the local machine.
> We prefer to use `0.0.0.0`, which is defined as a non-routable meta-address used to designate an invalid, unknown, or non applicable target.
> Using `0.0.0.0` is empirically faster, possibly because there's no wait for a timeout resolution. It also does not interfere with a web server that may be running on the local PC.

https://github.com/StevenBlack/hosts#we-recommend-using-0000-instead-of-127001

<details>
 <summary>...</summary>
@pgl @yous
@mitchellkrogza @funilrys
@StevenBlack
</details>

**Comment by pgl** [comment]
You can specify whatever IP you like with my list by using the query string parameter `useip`. eg:

 * https://pgl.yoyo.org/adservers/serverlist.php?useip=0.0.0.0

**Comment by hoshsadiq** [comment]
@TheWatcherofWays what vulnerabilities are you talking about? I don't see how "unroutable" could lead to a vulnerability? Any decent OS and/or DNS service should discard 0.0.0.0 and stop right there and then.

**Comment by hoshsadiq** [comment]
Closing as no response.
