### ISSUE TITLE
I suspect something is mining in batmanstream.net

### ISSUE THREAD

**Issue by Jellby** [hoshsadiq/adblock-nocoin-list#228]
### Website with example

Streams in batmanstream.net

### Domain causing the CPU spike

I don't know, high CPU usage starts a few seconds after video, and it has nice level 1 (on linux). "about:performance" in Firefox does not show high CPU usage. As far as remember this didn't happen a couple of months ago.

**Comment by hoshsadiq** [comment]
Sorry for the late reply. I don't see anything. Do you have an exact URL causing the high CPU levels?

**Comment by Jellby** [comment]
I guess the URLs change... Note that it's not on the homepage, but once you click your way down to some actual streaming. Right now I'm seeing it on http://live.drakulawidget.com/streamvideo10/rafael-nadal-live-streaming-4666454.html

Before clicking on the link on http://www.zorrostream.net/rafael-nadal-live-streaming.html:
![snapshot1](https://user-images.githubusercontent.com/7943459/40623450-7793eb24-62a7-11e8-96de-d758c625bf67.png)

A few seconds after clicking on the LSHStreams Link #1:
![snapshot2](https://user-images.githubusercontent.com/7943459/40623532-b03bd23e-62a7-11e8-8d78-db1b93be70f9.png)

It could be the streaming itself, but I didn't see such high usage some weeks ago, and other sites like youtoube give much more reasonable CPU (less than 1 out of 4).

**Comment by hoshsadiq** [comment]
Okay, I will have to look at this tonight when I'm home.

**Comment by hoshsadiq** [comment]
I'm unable to see anything suspicious. Are you using Flash to stream? That might cause issues.

@smed79 can you see if there's anything suspicious on that link?

**Comment by smed79** [comment]
Nothing suspicious for me, for that reason i did not react.

**Comment by hoshsadiq** [comment]
I will close this for now, if you have any more info I'm happy to look into it.

**Comment by Jellby** [comment]
Yes, I'm using Flash, is it possible not to use it? If you don't see anything worrying, I guess it's OK.
