### ISSUE TITLE
bmst.pw/2481915x30.js

### ISSUE THREAD

**Issue by PentagramTr** [hoshsadiq/adblock-nocoin-list#229]
https://lafmacun.net

Hi,
Please block this script and add it to the NoCoin filter.
Thank you.

`https://bmst.pw/2481915x30.js`

<details><summary>Screenshot</summary>

![laf](https://user-images.githubusercontent.com/34379403/40274514-d1c181e2-5be0-11e8-8b89-b43297f311fd.png)

</details>

<details><summary>Screenshot</summary>

![bms](https://user-images.githubusercontent.com/34379403/40274632-46925034-5be4-11e8-9ae3-3344b316cd08.png)

**Comment by hoshsadiq** [comment]
This was already merged in #230
