### ISSUE TITLE
kdowqlpt.info

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#24]
http://kdowqlpt.info/main.js

**Comment by hoshsadiq** [comment]
I'm a little confused. These domains are not working.

**Comment by MajkiIT** [comment]
@hoshsadiq hmmm it's strange. 8 hours ago it's works. So you can close isseu.

**Comment by MajkiIT** [comment]
Also dead
http://xbasfbno.info/
http://jyhfuqoh.info/ 
etc

**Comment by hoshsadiq** [comment]
Yup. They all are, but their whois is peculiar. All registered through namecheap, with WhoisGuard. I'm going to merge it as the domains expire next year, just in case they pop up again.

**Comment by SMed79** [comment]
> These domains are not working.

Check using [**#funceble**](https://github.com/funilrys/funceble/#funceble).

**Comment by MajkiIT** [comment]
@SMed79 All domains not show A record. All domain have Cloudflare DNS . I write issue to CF and they block this domains.
