### ISSUE TITLE
Add webmine.cz

### ISSUE THREAD

**Issue by kikz0rsk** [hoshsadiq/adblock-nocoin-list#245]
### Website with example

http://stream-a-ams1xx2sfcdnvideo5269.cz/okno.php?movie=NDc=&new_way

### Domain causing the CPU spike

http://webmine.cz - downloads scripts for execution
wss://webmine.cz (also via ws)
wss://wsservices.org (has been before, not sure if it is now)
wss://authedwebmine.cz (also via ws)

### Screenshot

![capture](https://user-images.githubusercontent.com/20465221/41055091-972a4c7e-69c0-11e8-9d49-e6a77eec57bf.PNG)

**Comment by kikz0rsk** [comment]
I've identified new domains from Developer Tools
wss://skencituer.com
wss://s3.site.flashx.cc/ (site.flashx.cc)

**Comment by hoshsadiq** [comment]
Thanks! Fixed

**Comment by Zyomich** [comment]
@hoshsadiq add http://play.pampopholf.com/app.js please. There is miner in this Java script.

**Comment by smed79** [comment]
@Zyomich https://github.com/hoshsadiq/adblock-nocoin-list/pull/249

Open a new issue for new site, don't post anywhere and always provide an example site(s).
