### ISSUE TITLE
Onlinevideoconverter.com has been set as a blacklist member, we want to appeal for this

### ISSUE THREAD

**Issue by avqd** [hoshsadiq/adblock-nocoin-list#250]
Hi,

1. A script was likely inserted by one of our devs without consent previously. We have check our site thoroughly to find no such scripts currently exist on the site.
2. As long as a user has Adblock installed, our conversion service cannot function normally as requests within the site has been blocked entirely.
3. We find that nocoin.txt has put our website onlinevideoconverter.com into the blacklist
4. We really hope you can help us resolve this problem, we want to appeal for this, if you need any information just feel free to ask us, we will reply asap.

Thank you.

Best Regards,
Email: contact@onlinevideoconverter.com
Keith

**Comment by hoshsadiq** [comment]
> A script was likely inserted by one of our devs without consent previously. We have check our site thoroughly to find no such scripts currently exist on the site.

If you truly believe this to be the case (which I don't particularly believe), I would revisit as I can still see mining requests happening. Happy to remove it once you've fully removed the scripts that mine without user consent.

**Comment by ZeroDot1** [comment]
https://www.virustotal.com/#/url/9080190eef2fb32601260dc5e16a3958eef28dd2daa2f4ff494209d8760d9148/community

**Comment by smed79** [comment]
@ZeroDot1 Please NO noise. I do not see the interest of posting these domain & subdomains here.

**Comment by ZeroDot1** [comment]
@smed79 I deleted it again, I just thought it could be helpful. Sorry.

**Comment by avqd** [comment]
Hi Hosh,

Can you please tell us where exactly do you see the mining requests or scripts? We're really hoping to resolve this fully and hoping you can point us in the right direction.

We've currently just double-checked all pages and all our code and still could not find any traces of it.  

Hi smed79, 

We've disabled the anti-adblock script as requested.

Please tell us if you need anything else. 

Thank you.

Best,
Keith

**Comment by smed79** [comment]
@hoshsadiq It is safe to remove onlinevideoconverter.com https://github.com/hoshsadiq/adblock-nocoin-list/pull/255

@avqd No suspicious activity allowed, to not get this commit reverted.

**Comment by avqd** [comment]
@smed79  We'll make sure of that, thank you very much!
@hoshsadiq Thank you for resolving the issue for us as well.
