### ISSUE TITLE
estream.xyz

### ISSUE THREAD

**Issue by BDubbB** [hoshsadiq/adblock-nocoin-list#251]
### estream.xyz

https://estream.xyz/5ht1pdqzus6q.html

### Domain causing the CPU spike

I don't know how to tell what domain is actually doing the mining. Perhaps you could inform me as to how to accomplish this task?

**Comment by ZeroDot1** [comment]
@hoshsadiq 
Simply add these domains and the problem is solved.
I hope the information is helpful to you.
```
play.estream.xyz
play.play.estream.xyz
s2.play.estream.xyz
s3.play.estream.xyz
```

**Comment by hoshsadiq** [comment]
@BDubbB I just pushed a fix. Thanks for reporting.

**Comment by BDubbB** [comment]
Thanks for your work, man. This seems like it's going to be a lifesaver.

**Comment by BDubbB** [comment]
The site seems to be eating up cpu again, like it's mining, but only when the video is playing.

**Comment by hoshsadiq** [comment]
Do you have a link as the link in the original post is not working anymore? Additionally, please open a new issue.
