### ISSUE TITLE
mining donates has be blocked

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#259]
![2018-06-26-coinhive miner](https://user-images.githubusercontent.com/5884000/41935137-fab770d2-7988-11e8-838b-da94dc022d03.png)

i do not can click start the mining

example address
`https://authedmine.com/media/miner.html?key=ZpmDZUFJhHdv1YZHpCHFWhAUQIGa67TV#`

ubo 1.16.10
chr 67.0.3396.99
w10

**Comment by smed79** [comment]
The purpose of [NoCoin adblock list](https://github.com/hoshsadiq/adblock-nocoin-list#nocoin-adblock-list) is to block mining (opt-in or out there is not different).

If mining is important to you just [whitelist](https://adblockplus.org/filters#whitelist) the site that are visiting in your adblock.

**Comment by KonoromiHimaries** [comment]
@smed79 this page does not start the mining automatically
that's why I think it's worth making a global exception for her
