### ISSUE TITLE
podrltid.info

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#26]
https://podrltid.info/main.js

**Comment by SMed79** [comment]
Is that it is necessary to create a new issue for each random domain?
Also If you have already submit a PR I think not need to open an issue.

see https://github.com/hoshsadiq/adblock-nocoin-list/pull/27#issuecomment-333570332

**Comment by MajkiIT** [comment]
`/^https:\/\/[a-z]{8,8}\.info\/main.js/$script`

**Comment by SMed79** [comment]
The **regex filter** will cause too false positives on websites that have nothing with the mining domains.

**Comment by hoshsadiq** [comment]
Yes. `main.js` is too generic.

I've never seen this happen, but I wonder if filter lists support blocking based on javascript objects/classes. I can't seem to find anything on Google, any ideas?

**Comment by gomoku** [comment]
Also this regex is bugged, as it has an unescaped dot, should be `\.js`
