### ISSUE TITLE
Piratebay mining alert

### ISSUE THREAD

**Issue by im3or** [hoshsadiq/adblock-nocoin-list#265]
Hello, I just started getting kaspersky alert about mining on www.thepiratebay.org whenever i search something.
Please into this & add it to filters.

![screenshot00576](https://user-images.githubusercontent.com/30718972/42304865-fbf59596-8045-11e8-9789-d227d866c3e3.jpg)

**Comment by smed79** [comment]
Mining is already killed by the CSP filter 
`$csp=child-src 'none'; frame-src *; worker-src 'none',domain=`
