### ISSUE TITLE
www.aioboot.com

### ISSUE THREAD

**Issue by gggirlgeek** [hoshsadiq/adblock-nocoin-list#268]
https://www.aioboot.com

<< Example of pages that are mining >>

https://www.aioboot.com/en/bob-ombs-modified-win10pex64/#List-of-software

### Domain causing the CPU spike

Unknown

###Comment
I use UBO and Nocoin filter list. I also have all third party scripts and frames blocked by default. This site was still able to freeze Firefox 52 and raise my CPU 60-90% for an hour.  I tested it twice. Closing this tab brought CPU down to 10%. The mining doesn't start for a few minutes (AFTER CLICKING "I Don't Care" to Adblock warning.)

Not willing to overheat my poor laptop again for a screenshot. Sorry.

Adding CoinMiner list solved the problem but I will not visit the site again.

**Comment by smed79** [comment]
@gggirlgeek Please test this filter 
```
$csp=worker-src 'none',domain=aioboot.com
```

@okiehsch Nothing suspicious for me, would you please check.

**Comment by okiehsch** [comment]
I don't see anything mining related in the source on my end and my CPU looks normal too.

**Comment by smed79** [comment]
Thank you.

**Comment by hoshsadiq** [comment]
I don't see it either. @gggirlgeek closing, if you can show us a link where the mining the happen, feel free to comment on here and I'll reopen it.

**Comment by nguyentumine** [comment]
I have a question, I'm the author of aioboot.com website. I see this domain in the list. But I only put Google Adsense ads. Can you tell me what the problem on my site is?

**Comment by nguyentumine** [comment]
Don't use my software and never visit my website again.

Why don't you think it's a browser bug?

**Comment by smed79** [comment]
@nguyentumine 

`aioboot.com` Will be removed, sorry for the false positive.

> Don't use my software and never visit my website again.

Do not rush, because what you are saying here just make you ridiculous :unamused:
