### ISSUE TITLE
estream.xyz - again

### ISSUE THREAD

**Issue by BDubbB** [hoshsadiq/adblock-nocoin-list#271]
The weird thing about it is that it is only hitting one core at a time, but changing cores once or twice every second, for about 40% C.P.U. usage. I'm not absolutely sure it is mining, as I don't know how to tell, but it is not normal activity for video streaming.

### Website with example

https://estream.xyz/tkdzqocj0yhi.html

**Comment by hoshsadiq** [comment]
Should be fixed now. I will
