### ISSUE TITLE
Unblock broadcastt.xyz

### ISSUE THREAD

**Issue by Nerg4l** [hoshsadiq/adblock-nocoin-list#272]
Hi!

I would like to report an incorrectly removed content.

```
/^(https?|wss?):\/\/([0-9a-z\.-_]+)\.(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|ovh|party|pro|pw|racing|review|rocks|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)(\.)?\/(.*)/$third-party,websocket,domain=~myinterview.com|~webtorrent.io
```

This rule blocks every third party websocket from xyz domains except for myinterview.com and webtorrent.io domains.

The site broadcastt.xyz provides pubsub WebSockets to help developers create realtime applications. (It is still in development.)

You can find an example [here](https://nergal.xyz/easy.html) where with Chrome AdBlock extension the socket is blocked `net::ERR_BLOCKED_BY_CLIENT` and I only enabled the crypto mining protection.

I would be very happy if you could whitelist the site.

Thanks,
Laszlo

**Comment by hoshsadiq** [comment]
Sorry I haven't looked at this yet. I will look at it this weekend hopefully!
