### ISSUE TITLE
[request] Convert to uBlock format

### ISSUE THREAD

**Issue by bryce-lynch** [hoshsadiq/adblock-nocoin-list#274]
Since the NoCoin list "optimized for uBlock" is minimal, I'd appreciate if you could either publish the main (Adblock) list in uBlock format also, or provide a script or other means to manually convert it.

**Comment by hoshsadiq** [comment]
You can simply import the main adblock list, uBlock will automatically use both

**Comment by bryce-lynch** [comment]
Ah, I had already tried that and it didn't work, so I assumed it wasn't compatible.
I've tried again now and it works fine. Guess I was using the URL of the github page instead of the raw list... Thanks for your work BTW.
