### ISSUE TITLE
a-o.ninja error 

### ISSUE THREAD

**Issue by OtakuPL** [hoshsadiq/adblock-nocoin-list#278]
### Website with example

https://a-o.ninja/

### Domain causing the CPU spike

https://a-o.ninja/
https://a-o.ninja/anime/boku-no-hero-academia-3-2018/16
Error 2 does not play literally any player with the filters enabled anti miner. Home no longer uses the miner more than two months.

### Screenshot

http://scr.hu/2ci4/afg28

    Browser/version: chrome 68.0.3440.75 (64-bit)
    uBlock Origin version: [here]

Settings
http://scr.hu/2ci4/qoerr

Notes;
Do not operate any video player.

**Comment by smed79** [comment]
No issue here https://i.imgur.com/isr3W0K.gifv

Are you the webmaster?

**Comment by OtakuPL** [comment]
Hi.
it's about the adblock plugin https://www.getadblock.com/
Adblock Plus works well.

**Comment by smed79** [comment]
The same with AdBlock (which use ABP engine) https://i.imgur.com/feJ7Xpi.gifv

**Comment by OtakuPL** [comment]
Google browser chrome 68.0.3440.75 64bit windows 10 home 64bit
there is an error of 100%

**Comment by OtakuPL** [comment]
1. http://scr.hu/2ci4/fum11 Adblock config http://scr.hu/2ci4/rkdmi
2. http://scr.hu/2ci4/290k2 config http://scr.hu/2ci4/ruie4

I have checked many times, this cryptocurrency filter blocks players.

**Comment by smed79** [comment]
We cannot help you if we cannot reproduce the issue.

**Comment by OtakuPL** [comment]
But what should I give you? I sent screen, system, browser what else?
At 100% this is a problem with mineral filters.
There are no cryptocurren excavators on the site a-o.ninja, so please remove all mention of it in filters and it will work.

**Comment by hoshsadiq** [comment]
Can you try disabling AdBlock and use uBlock Origin with the same filters?

**Comment by OtakuPL** [comment]
? chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.1blockpkg
are these letters? because I do not know..

**Comment by hoshsadiq** [comment]
No, I meant, disable adblock addon, and install [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) and add/enable the same filters.

**Comment by OtakuPL** [comment]
Can anyone help?

**Comment by smed79** [comment]
> Home no longer uses the miner more than two months

Already lose our trust, we need more time to be sure.

> Can anyone help?
> Adblock Plus works well

Help your self, use uBlock₀ or Adblock Plus if they works well...

**Comment by OtakuPL** [comment]
I am the owner of a-o.ninja about traffic and users. I will never go back to cryptocurrency excavators. The traffic on the site has diminished a lot because of an adblock error. You are the last resort for this portal. If the players do not work, the entire site loses the sense of existence.

That's why I want to fix the error. this error has been for several months. I can not wait any longer because I will have to close the portal due to lack of entries. 

people from the Polish adblock support team sent me to you to solve this problem.
(sorry, I write from the translator).

**Comment by krystian3w** [comment]
> Where does uBlock Origin have a block filter for a cryptocurrency excavator? because I can not see him anywhere there?

[https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt&title=NoCoin%20Filter%20List) - click and uBlock Origin should add list.

if no work subscribe from: https://www.certyficate.it//adblock/ (before the last row / second from the end of the row) - from there it must work subscribe.

**Comment by smed79** [comment]
> I am the owner of a-o.ninja

I asked you that here https://github.com/hoshsadiq/adblock-nocoin-list/issues/278#issuecomment-409248692

> I will never go back to cryptocurrency excavators.

Ok, just prove'**¹**' that you are the site owner then we will remove a-o.ninja from the list.

---
[1] Upload this file "[nocoin.txt](https://github.com/hoshsadiq/adblock-nocoin-list/files/2257404/nocoin.txt)" to the root of the site.

**Comment by OtakuPL** [comment]
> [1] Upload this file "nocoin.txt" to the root of the site.
Ok, https://a-o.ninja/nocoin.txt

**Comment by krystian3w** [comment]
* https://portableapps.com/redirect/?a=FirefoxPortable&s=s&p=&n=Mozilla%20Firefox,%20Portable%20Edition&d=ddgsfpa&f=FirefoxPortable_61.0.1_Polish.paf.exe
* https://portableapps.com/downloading/?a=GoogleChromePortable&n=Google%20Chrome%20Portable&s=s&p=&d=pa&f=GoogleChromePortable_68.0.3440.84_online.paf.exe

And try again install in portable AdBlock - maybe broken only for your computer if on have signals for users.

**Comment by smed79** [comment]
@OtakuPL Wait @hoshsadiq to approve the PR #279  

PS: _You can remove the file "nocoin.txt" from the root of your site_.

**Comment by OtakuPL** [comment]
Everything works. Thank you the most!
