### ISSUE TITLE
github always reports false updates

### ISSUE THREAD

**Issue by Sadi58** [hoshsadiq/adblock-nocoin-list#281]
I use a hostsblock script with a number of lists like yours used as sources, checking for updates periodically and updating the hosts file (or another file used as add-in via dnsmsaq) for any updates found.

I've noticed that somehow github always reports updates, even when there is no change in the list here. For example, https://github.com/ZeroDot1/CoinBlockerLists has recently moved to gitlab and I no longer get such false update reports for that list, but you list is reported as updated every time it's checked.

Do you have any idea what might be causing this? Any idea as to how this can be stopped?
Or do we have to live with this unless and until this issue is resolved by github (maybe this should be reported as an issue to them) or moving to gitlab maybe?

**Comment by hoshsadiq** [comment]
What mechanism do you use to check for updates? 

> Or do we have to live with this unless and until this issue is resolved by github (maybe this should be reported as an issue to them) or moving to gitlab maybe?

Wouldn't be able to give you a definite answer unless I find out what's causing the issue, but I think likely yes, we'll have to wait for GitHub to fix the issue. I'll be happy to raise an issue with GitHub once I know more about the problem.

**Comment by Sadi58** [comment]
With some beginner level scripting skills, I have merely attempted to add some zenity-based GUI elements for a hostsblock script, and I think it looks at the modification time provided by the server.
Maybe you can understand it better here:  https://github.com/Sadi58/hostsblock/blob/master/indicator/hostsblock-check-updates

**Comment by hoshsadiq** [comment]
You are correct. It looks like GitHub is not returning valid responses for the `If-Modified-Since` header (should be conditional, and return 304 if the file hasn't been edited since that time, otherwise 200). I will email GitHub support, however, I can't do anything else besides that. If they choose to address it or not that won't be up to me unfortunately. If they give me an answer that solves your issue, I will reply to this issue.

**Comment by hoshsadiq** [comment]
@Sadi58 Seems they do not support that with the raw files. They do if you use the GitHub API, e.g.:
```
curl -Ls -H 'Accept: application/vnd.github.VERSION.raw' https://api.github.com/repos/hoshsadiq/adblock-nocoin-list/contents/nocoin.txt -H "If-Modified-Since: Tue, 18 Aug 2018 10:53:02 GMT"
```

Be aware, that the header `Accept` is required if you want the raw file.

**Comment by Sadi58** [comment]
Thanks a lot!
I'll try to incorporate it (although it seems beyond me;-)
