### ISSUE TITLE
kissanime.ru mining scripts

### ISSUE THREAD

**Issue by runboy93** [hoshsadiq/adblock-nocoin-list#285]
http://kissanime.ru/

`http://basepush.com/ntfc.php?p=1900612`

https://www.virustotal.com/#/url/fbb0dba3ab26f5e48a5f1f48a323e2714d248aed7819d0db9291ca971e485413/detection

`rotumal.com/5/1616188`, not sure about this one atleast it's included with script.

Sources:

https://www.reddit.com/r/KissAnime/comments/96mypr/kissanime_mines_cryptocurrency_on_your_machine/

https://www.reddit.com/r/animepiracy/comments/96ov7g/kissanime_mines_cryptocurrency_on_your_machine/

**Comment by smed79** [comment]
`basepush.com` is blocked  in [easylist](https://easylist-downloads.adblockplus.org/easylist.txt) as an adserver (propellerads) alos the popup source from`rotumal.com`  (reported first time here [#p136310](https://forums.lanik.us/viewtopic.php?p=135981&hilit=fortpush.com+ntfc.php#p135981) & [#p138286](https://forums.lanik.us/viewtopic.php?p=138286&hilit=rotumal.com#p138286)).

@okiehsch Are face of any mining activity here?

**Comment by smed79** [comment]
Merci.

**Comment by smed79** [comment]
No mining activity here, you can close this issue.
