### ISSUE TITLE
Another miner found

### ISSUE THREAD

**Issue by somfuckingname** [hoshsadiq/adblock-nocoin-list#286]
http://fitgirl-repacks.site/donate-by-mining/

blog page

Avast! blocks it.

![2018-08-19_183825](https://user-images.githubusercontent.com/42525664/44315511-1aa8b300-a3e2-11e8-991e-a456cea77ada.jpg)

**Comment by smed79** [comment]
After checking... The site does not **automatically redirect** you to the mining page or **force** you to mine to have access to the contents or use a **third party** mining service !! 

Yes, we block opt-in and opt-out mining but not blindly. If you have voluntarily clicked a link to browse this page, should we block **donation** just to harm them ?
