### ISSUE TITLE
add `ppoi.org`  to list please

### ISSUE THREAD

**Issue by hye** [hoshsadiq/adblock-nocoin-list#32]
`ppoi.org` is a `coinhive` copycat in China
REF:https://ppoi.org/documentation

**Comment by SMed79** [comment]
Do you have an example site using `ppoi.org`?

**Comment by hye** [comment]
Sorry, I did not know that,( I knew the ppoi when they post ad in some online community) but their API is just like coinhive
[simple ui](https://ppoi.org/documentation/simple-ui)
```
<script src="https://ppoi.org/lib/miner.min.js" async></script>
<div class="projectpoi-miner" 
	style="width: 256px; height: 310px"
	data-key="YOUR_SITE_KEY">
	<em>please disable Adblock!</em>
</div>
```
[captcha](https://ppoi.org/documentation/captcha)
```
<form action="?" method="post">
	<!-- other form fields -->

	<script src="https://ppoi.org/lib/captcha.min.js" async></script>
	<div class="projectpoi-captcha" data-hashes="1024" data-key="SITE_KEY">
		<em>Loading Captcha...<br>
		If it doesn't load, please disable Adblock!</em>
	</div>

	<input type="submit" value="Submit"/>
</form>
```
etc...

**Comment by SMed79** [comment]
The maintainer of the list needs a valid third-party URL where he can see `ppoi.org` in action.

**Comment by hoshsadiq** [comment]
Looking at the [js file](https://ppoi.org/lib/projectpoi.min.js) that needs to be embedded, I think simply having a thirdparty block on `ppoi.org` and `projectpoi.com` should be plenty, but yes, we need to see it in action to be able to fully understand the filters to add. For now I'll add ppoi.org and projectpoi.com

**Comment by passjs** [comment]
In this kind of case, you don't need a proof !!
nocoin list is out-of-date, please add
```
||ppoi.org^$third-party
||projectpoi.com^$third-party
```

**Comment by SMed79** [comment]
@hoshsadiq Probably it is safe to merge. What do you think?

**Comment by hoshsadiq** [comment]
Sorry, the problem isn't proof. I added those two to the list when I saw this issue. I was just hoping someone could provide an example so I could look at the requests the scripts are making to make sure all necessary filters can be added.
