### ISSUE TITLE
vev.io

### ISSUE THREAD

**Issue by ahoura** [hoshsadiq/adblock-nocoin-list#323]
Hi,

It seems that due to #317 , vev.io has inherited tvad.me's filters. This is not necessary as vev.io is not running any of the previous scripts that were found on tvad.me. 

If you would like to discuss this further please feel free to get in touch; the filters are currently interfering with other site functions.

Thanks for your time

**Comment by smed79** [comment]
I do not trust a site which is full malvertising revolving script and popups.

If any feature is broken, provide details and explain how to reproduce.

**Comment by ahoura** [comment]
@smed79 sure, here is a list of features not working properly:
1. Recaptcha does not load properly as a result of "worker-src 'none'" filter. 
**Affected Components**
- Authentication/Registration page
-- you may recreate the issue by visiting any of these two pages
https://vev.io/auth/login
https://vev.io/auth/signup

- Video player page: 
-- You can recreate this issue by either connecting to a VPN or refreshing the player page rapidly (2/3 times a second should trigger it), it will prompt a recaptcha validation before showing the player.
this is particularly a huge concern of ours as users connected to a VPN provider will not be able to watch any videos: 
https://vev.io/543v12g6mw30

2. Websockets have also been blocked, we use websockets to show video conversion progress. You can recreate the issue by uploading a video and waiting for the conversion progress.
https://vev.io/upload
