### ISSUE TITLE
All json files from github.io blocked

### ISSUE THREAD

**Issue by karellodewijk** [hoshsadiq/adblock-nocoin-list#332]
I have a website with some static resources on github.io. With addblock enabled, all js/css/images/etc get through but json files, in itself harmless files, get blocked by this filter.

Filter rule that blocks the files as reported by Adblock on chrome:
||github.io^$third-party,xmlhttprequest,domain=~facebook.com|~github.com|~tumblr.com
NoCoin Filter List

Example links:
https://wottactic.com/wot2
https://wottactic.com/player/505943778

**Comment by domoritz** [comment]
This is breaking many application on the web right now.

**Comment by domoritz** [comment]
@smed79 Thanks for getting back to me. I created https://github.com/hoshsadiq/adblock-nocoin-list/issues/334

**Comment by karellodewijk** [comment]
There's no anti-adblock on the site, the page that has the warning gives it because it can't load the json file, it doesn't even have ads at all.

Pls exclude wottactic.com, wowstactic.tk and gametactic.org and subdomains on those.

Note I just want the site to properly load the json files it needs, I'm fine with adblock blocking ads.
