### ISSUE TITLE
Domain zone exclusion

### ISSUE THREAD

**Issue by a2mta** [hoshsadiq/adblock-nocoin-list#339]
Hi guys.
After installing uBlock i noticed, that one of the rule in your list is blocking the whole domain zone in which is our domain. And this rule is breaking websockets in our services. 

Is it possible to exclude "**site**" domain zone from this regex ?

/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)\/(.*)/

Thank you.

**Comment by hoshsadiq** [comment]
What is your service? We will exclude it separately.

**Comment by hoshsadiq** [comment]
Closing as there's no response. You're welcome to give us more information to whitelist your site.
