### ISSUE TITLE
New Websites

### ISSUE THREAD

**Issue by giantoppai** [hoshsadiq/adblock-nocoin-list#353]
hotbit.io is a cryptocurrency exchange that secretly mines in your browser.
bitcoinqrcodegenerator.win is a site that provides false QR codes to their own bitcoin address.

**Comment by smed79** [comment]
No suspicious activity for me.

@okiehsch do you confirm?

**Comment by hoshsadiq** [comment]
There's a websocket running on the hotbit.io but I don't think it's a mining related.

>  bitcoinqrcodegenerator.win is a site that provides false QR codes to their own bitcoin address.

While this is not a nice practice, I am reluctant to add it to this list. I want to keep this list purely for cryptocurrency mining. I would say should be on uBlock's badware list or one of the other lists that are there to block bad sites.

**Comment by giantoppai** [comment]
> I would say should be on uBlock's badware list or one of the other lists that are there to block bad sites.

Thanks, I posted it on uBlock for `bitcoinqrcodegenerator.win`.
