### ISSUE TITLE
whitelist matt-kruse.github.io/socialfixerdata

### ISSUE THREAD

**Issue by filbo** [hoshsadiq/adblock-nocoin-list#359]
Please whitelist matt-kruse.github.io/socialfixerdata/ for xmlhttprequest.

A user reports (on a [group message](https://www.facebook.com/2060323954036475) for which you would have to join a group) that this list is blocking his access to [Social Fixer](https://socialfixer.com) features.

Note: I haven't been able to reproduce this myself, despite adding nocoin to my uBO configuration and enabling it on facebook.com.  So user's analysis / claim that it's caused by nocoin is dubious.

My (no-repro) config: Opera-developer 59.0.3209.0, uBO v1.17.0, SocialFixer 23.0.0, LinuxMint 17.3 x86_64.  FWIW.

**Comment by smed79** [comment]
Ask the user to submit an Adblock Plus [issue report](https://adblockplus.org/en/getting_started#false-positives) and post the link here.

**Comment by hoshsadiq** [comment]
> If your list is blocking *.github.io and you are selectively whitelisting specific sites

`*.github.io` is whitelisted on `facebook.com` (see https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt#L637) so perhaps something else is blocking the request. Do you have any more details you can give us?

**Comment by filbo** [comment]
These are his additional replies since I asked for more info:

> Paul Carroll:
> 
> I just added an exception rule (which solves the problem) to the My Filters tab in the uBO dashboard.
> 
> `@@||matt-kruse.github.io/socialfixerdata/filters.json$xmlhttprequest,domain=behind-the-scene`
> 
> The uBO logger shows `https://matt-kruse.github.io/socialfixerdata/filters.json` being blocked (in red) any time I open Social Fixer options. Without the exception rule (above), the Filters option 'page' just stops, right before the header "Filter Subscriptions". With the exception rule, it works fine.
> 
> Here's a screenshot from the uBO logger, showing the default no rule (red/blocked), and with the exception rule (green/allowed).
> ![ubo-exception-rule](https://user-images.githubusercontent.com/3022180/52393872-14c09000-2a5d-11e9-9636-202f0bc81398.jpg)
> Like · Reply · Wednesday, February 6, 2019 at 1:24 AM

> Paul Carroll:
> 
> And a screenshot of the details when I click on the blocked red entry...
> ![ubo-blocked-detail](https://user-images.githubusercontent.com/3022180/52393882-22761580-2a5d-11e9-9c4a-12166c1aefa0.jpg)
> Like · Reply · Wednesday, February 6, 2019 at 1:25 AM

**Comment by filbo** [comment]
It looks like the rule that it says is triggering, should not trigger.  But I don't understand the subtleties of the adblock syntax well enough to be sure, and his screenshot says it is happening.

Hmmm, reading docs, I think I see.  The way the extension is firing the xhr, uBO can't tell that it came from the FB page.  So the exception which says 'allow access to github.io when it came from FB' does not match.

And, I imagine that generally allowing github.io to behind-the-scenes code would provide a handy place for malware (such as the crypto coin 'miners' you aim at) to stash their code, to avoid you.  bleah.

So I will again ask that you whitelist the 3rd level domain, `matt-kruse.github.io`, not the 2nd, for 'behind-the-scenes' access.  For that to be a hole, malware people would have to have control of the 3rd level domain; which is of course possible by various trickery and stuff, but I'm sure there are dozens of easier targets, so it doesn't actually open a 'useful' (to mal-people) hole.

**Comment by smed79** [comment]
> why would they submit an Adblock Plus problem report?

an Adblock Plus [issue report](https://adblockplus.org/en/getting_started#false-positives) will be provide a useful details to investigate the issue (you can use a [portable version of browser](https://portableapps.com/apps/internet) for testing). Also does the user have the same issue if testing using other ad blockers as Adguard, AdBlock or Adblock Plus?

**Comment by filbo** [comment]
Hi,

I just noticed that this fix was incomplete.  The fixer rule reads:

`@@||matt-kruse.github.io/socialfixerdata/filters.json$xmlhttprequest`

when it should be:

`@@||matt-kruse.github.io/socialfixerdata/$xmlhttprequest`

or at least:

`@@||matt-kruse.github.io/socialfixerdata/*.json$xmlhttprequest`

[Social Fixer](https://socialfixer.com) uses {filters,hideable,news,tweaks}.json, and may add others in the future, including potentially non-JSON.  The site currently has some *.html, *.gif, *.png files, but those are accessed through `<a>` / `<img>` so perhaps already unaffected.

There is no sensible reason to block a named, responsibly owned `github.io` subdomain.  Were it some day to become a mal-site, of course you would then remove the exception completely; but it is not.

**Comment by filbo** [comment]
Thanks!
