### ISSUE TITLE
Request to remove our site

### ISSUE THREAD

**Issue by goodolddownloads** [hoshsadiq/adblock-nocoin-list#36]
Hello, our site (https://goodolddownloads.com/) made it onto your filter list: `goodolddownloads.com/js/dolladollabillz.js`

Our miner is **OFF by default and must be enabled by the visitor themselves**. It DOES NOT run unless the users enables it -- it is optional on our site (unlike many others implementing miners). 

Can you please consider removing us from your filter list? Thank you.

**Comment by SMed79** [comment]
@hoshsadiq I am in favour to remove `goodolddownloads.com` https://github.com/hoshsadiq/adblock-nocoin-list/pull/19/
See https://github.com/uBlockOrigin/uAssets/pull/725#issuecomment-332876390

**Comment by hoshsadiq** [comment]
I agree! You guys are doing the right thing. I'll remove it now.

**Comment by hoshsadiq** [comment]
Removed.
