### ISSUE TITLE
ovid.icu 

### ISSUE THREAD

**Issue by hdvid** [hoshsadiq/adblock-nocoin-list#377]
i see everytime i am using another domain u block it..this list isnt for mining block ? i dont have any mining script on the website..why u still blocking my domain ?

**Comment by smed79** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/pull/376#issuecomment-471312561

**Comment by hdvid** [comment]
but this is nocoin adblock..and i dont have any mining on the website...

**Comment by smed79** [comment]
If I am not mistaken, this list is our (_adblock users_) and it is we who decide what to block or not for the benefit of adblock users.

**Comment by hdvid** [comment]
good logic...
NoCoin adblock list
This is an adblock list to block "browser-based crypto mining".
and u blocking sites thats not even use crypto mining..well done dude ! as u said its ur list..but u can rename it to block everything we wants..xD
