### ISSUE TITLE
api.nyda.pro

### ISSUE THREAD

**Issue by artdude543** [hoshsadiq/adblock-nocoin-list#380]
Good Evening,

Hope your day is going well. Would it be possible to have my domain `nyda.pro` added to the white/ignore list please for WSS connections? Your Regex for all WSS connections seems a tad over ambitious as `.pro` is highly used for web-based applications which rely on sockets. But this check is breaking a role out for my users who have this filter, leading to false bug reports on issues.

But it would be awesome if the domain could be whitelisted. If you need context for the request, I have a WebSocket backend for applications I curate to use for live events on panels.

Thank You!

**Comment by hoshsadiq** [comment]
What is your use case? I don't see anything on your site besides a coming soon message. For all we know what's coming is a coin miner so unless you have a valid reason to be on the white list, it will stay off it.

**Comment by artdude543** [comment]
I did say the use case but I'll digest some more.

I have an API which all my frontend applications rely on which is built on HapiJS which uses NES for subscription-based events which allow for live triggers/updates etc... The main project Nyda is working on is a new chatbot for Mixer/Twitch/YouTube etc... for crossovers to allow easier management for content creators and the socket powers the overlay system/alerts and other components.

I'd never see the day of myself using a miner, never agreed with them in the first place and it's a waste of resources. The API runs on a sub-domain, but there is no coin miner or any miner _"coming soon"_ as you _suggested_.

I'm fairly sure that use case is enough to warrant the exclusion.

**Comment by hoshsadiq** [comment]
Do you have an example page?

**Comment by artdude543** [comment]
I am happy to share the API which is located at `api.nyda.pro` but an example site using said API is under a Non-Disclosure Agreement. But you can test hitting the API with a NES client example connection logic here `https://runkit.com/artdude543/5c9a424176d4b00013caad6b`

**Comment by smed79** [comment]
@hoshsadiq I do not see any problem to add an exception rule here.

You can add
```
@@||api.nyda.pro^$websocket
```
