### ISSUE TITLE
Google Recaptcha Issue

### ISSUE THREAD

**Issue by ahoura** [hoshsadiq/adblock-nocoin-list#382]
Hi,

It seems that google.com and recaptcha.net are being blocked by your [filter](https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt) list.
Since ads are not hosted via google.com or recaptcha.net a correction would be appreciated as users are having difficulty validating themselves due to this.

Thanks

**Comment by smed79** [comment]
Hi, 

our mind reading device is broken, please provide an example where google recaptcha is blocked?

**Comment by ahoura** [comment]
Thank you for getting back to me.

here is an example link: https://vev.io/6ko92j45exrp. 
google recaptcha fails to load from https://recaptcha.net/recaptcha/api.js?render=[KEY], and the player fails to load as a consequence.

I confirmed its being blocked by your list using [Adblock](https://getadblock.com/).

**Comment by smed79** [comment]
Does adding
```
@@||recaptcha.net/recaptcha/api.js$script,domain=vev.io
```
fix the problem for you?

**Comment by ahoura** [comment]
Hi,

not sure if you have noticed but recaptcha is still not working properly on the page: https://www.dropbox.com/s/2eeu7mrjvbxsjp1/Screenshot%202019-05-10%2006.11.32.png?dl=0

Could you remove vev.io from your list completely? this domain has *never* had any coin mining scripts installed on it.

Thanks
