### ISSUE TITLE
Google Recaptcha Issue

### ISSUE THREAD

**Issue by ahoura** [hoshsadiq/adblock-nocoin-list#383]
Hi,

Seems like issue #382 was closed preemptively.
recaptcha is still not working properly on the page as its visible in the screenshot below: https://www.dropbox.com/s/2eeu7mrjvbxsjp1/Screenshot%202019-05-10%2006.11.32.png?dl=0

Could you kindly remove vev.io and vidup.io from your list completely? These domains have never had any coin mining scripts installed on them.

Thanks

**Comment by hoshsadiq** [comment]
I've just checked on a clean browser with just this list, and recaptcha works fine on the link you gave in #382. Can you check using ublock origin as it will tell you which filter is blocking it (if any).

**Comment by ahoura** [comment]
The issue doesn't seem to be reproducing at the moment, sorry for the trouble, thank you for your time.
