### ISSUE TITLE
Request to Unblock webchain.network

### ISSUE THREAD

**Issue by mat592** [hoshsadiq/adblock-nocoin-list#384]
I created an issue at https://github.com/hoshsadiq/adblock-nocoin-list/issues/319#issue-374723083 about unblocking the above mentioned site a few months ago which was executed right and closed. But to my surprise, webchain.network was added again to the blocked list a few days ago https://i.imgur.com/BIkrWP6.png
I would like to make it very clear that site is simply a Webchain coin site and neither is it a mining site as assumed nor supporting/running any background JavaScript mining. Thus, I kindly request you to consider removing it from this list https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt again.

**Comment by smed79** [comment]
Sorry for the fp.
