### ISSUE TITLE
Merge with CoinBlockerLists

### ISSUE THREAD

**Issue by manuelfr51** [hoshsadiq/adblock-nocoin-list#386]
Great job on continuing nocoin work,and glad that this list is used on adguard adblocker,  would be great to add the host list used on CoinBlockerLists that is much more extensive (22821 domains)
https://gitlab.com/ZeroDot1/CoinBlockerLists/blob/master/hosts

**Comment by ZeroDot1** [comment]
Hi @manuelfr51,
Thank you very much for using the CoinBlockerLists, it is not a good idea to merge the lists, because the projects are different approaches to prevent mining.
The lists from @hoshsadiq  are for browser-based mining only.
My lists are especially designed for use in professional networks.
By the way @hoshsadiq , very good work, keep up the good work!

@manuelfr51 for more details about the CoinBlockerLists have a look at the official homepage: https://zerodot1.gitlab.io/CoinBlockerListsWeb/

**Comment by smed79** [comment]
@manuelfr51 

"NoCoin list" is a "_browser-based mining_" as said in the [README](https://github.com/hoshsadiq/adblock-nocoin-list#nocoin-adblock-list). It's does not block "clean pool sites" also to avoid false positive we do not blind adding domains, we need proof before adding, changing, moving or removing any filter or domain (see https://github.com/hoshsadiq/adblock-nocoin-list/issues/253 / https://github.com/hoshsadiq/adblock-nocoin-list/issues/44 / https://github.com/hoshsadiq/adblock-nocoin-list/pull/288)

For example `f2pool.com` is blocked in "CoinBlockerLists". Can you provide an example site using `f2pool.com` for mining cryptocurrency in your browser? No not sure ...

> much more extensive (22821 domains)

[PyFunceble](https://github.com/funilrys/PyFunceble) by @funilrys say that there is [7479](https://pastebin.com/raw/YZ8GN9AF) inactive domains and no nobody know how many false positive.

No one can denies the good job down by @ZeroDot1 but unfortunately and the disadvantage for the list is that any domain that has the words "`coin`", "`crypto`", "`mining`" or "`pool`" is suspect and have to blocked with it's subdomains. The maintainer is adding domains based on VT [search](https://www.virustotal.com/gui/domain/semipool.com/relations) without testing, checking or having a proof ...

If not and i am wrong, I will be happy to know for what reason "CoinBlockerLists" is blocking `wiki.multipool.us`, `financeforum.ru`, `forum.bitcore.io`, [coinbase.com](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/37), `bitcoinwallet.com`, `satowallet.com`, `blog.minergate.com` ... even if they are not mining or used for mining. 

@ZeroDot1 You have typo and invalid domains in your list

```
$ grep -E '\.\.|\.comwww\.' hosts
0.0.0.0 ethereum..miningpoolhub.com
0.0.0.0 europe.equihash-hub..miningpoolhub.com
0.0.0.0 f2pool.comwww.btcguild.com
0.0.0.0 fcn-mro.pool..minergate.com
0.0.0.0 jjj.258.comwww.btc.com
0.0.0.0 ulinix.comwww.btc.com
0.0.0.0 us-east.cryptonight-hub..miningpoolhub.com
0.0.0.0 www.f2pool.comwww.btcguild.com
0.0.0.0 www..majanetwork.com
0.0.0.0 www..miningpoolhub.com
0.0.0.0 www..moneroocean.stream
```
`comwww` should be splitted to a new break line.
`..` should `.` (_one dot only_).

@hoshsadiq I let you close this issue if you have nothing to add.

**Comment by ZeroDot1** [comment]
`

> The maintainer is adding domains based on VT search without testing, checking or having a proof ...

`
What??? i check before adding every domain.
Unfortunately sometimes false positives happen.
@smed79 Thanks for your bug report, I will check everything and with the next update all bugs you listed will be fixed.

**Comment by smed79** [comment]
> i check before adding every domain

Ok.

**Comment by ZeroDot1** [comment]
@smed79 Thanks, I hope my work helps a lot of internet users in our universe :D

Soo, I fixed all the bugs you listed.
I have planned the update for next week, at the moment I can't publish it yet, because I still have to check some new domains.
