### ISSUE TITLE
request to unblock https://balena-io.github.io/etcher/

### ISSUE THREAD

**Issue by nazrhom** [hoshsadiq/adblock-nocoin-list#388]
Hello, we currently use github pages to host metadata about available version of etcher that the website (https://www.balena.io/etcher/) can fetch and render links to. We noticed that something on this list is blocking our request to https://balena-io.github.io/etcher/scrutinizer.json causing users with AdBlock or other Ad blocking software to be unable to see the new versions.

Would it be possible to add this to the whitelist?

**Comment by nazrhom** [comment]
We temporarily mitigated the issue by fetching the file directly from `https://raw.githubusercontent.com/balena-io/etcher/gh-pages/scrutinizer.json` which seems not to be blocked, is this the correct way forward?

**Comment by hoshsadiq** [comment]
Done. Sorry about that.

**Comment by nazrhom** [comment]
@hoshsadiq thank you so much for the quick response :)

**Comment by ZeroDot1** [comment]
@nazrhom @hoshsadiq I have added the URL to my filter to prevent blacklisting in the CoinBlockerLists.
