### ISSUE TITLE
ardintcoin Scam...

### ISSUE THREAD

**Issue by decembre** [hoshsadiq/adblock-nocoin-list#389]
### Website with example

`https://french-streams.com/938-atlanta-saison-2.html`

### Domain causing the CPU spike

<< The domain that's actually doing the mining >>
ardintcoin.com

**Comment by smed79** [comment]
Hi, 
I can't see any mining related activity on `french-streams.com` and no requests from `ardintcoin.com`

Please, submit and post here the link of an Adblock Plus [issue report](https://help.eyeo.com/en/adblockplus/report-an-issue).

**Comment by decembre** [comment]
here a screen shoot of it on this site when you want show a movie:
![Ublock - Ardintcoin com - 2019-07-05_184453](https://user-images.githubusercontent.com/868778/60735973-b1785280-9f55-11e9-9d3b-f3ad7b7099df.png)

You can have too (but easy to close):
![Ublock - Crop - 2019-07-05_184356](https://user-images.githubusercontent.com/868778/60736033-eab0c280-9f55-11e9-9549-c9b58ce883b7.png)

**Comment by smed79** [comment]
Describes the steps to reproduce.

**Comment by decembre** [comment]
Step by step:
Open a movie to watch 
click play
first time you can have just the inscription pub, but if you retry to play another server that's this damn ardintcoin scam which take the place ....

I go to the easylist forum to put a request too.
Anyway, on Ublock Orign, they seems add a rule for that:
<a href="https://github.com/uBlockOrigin/uAssets/issues/5924">Ardintcoin Scam on streaming sites</a>

**Comment by smed79** [comment]
The filters added to ubo target the popups (already fixed in [**Liste FR**](https://adblockplus.org/subscriptions)).
