### ISSUE TITLE
block p2p on player

### ISSUE THREAD

**Issue by Vladislavik** [hoshsadiq/adblock-nocoin-list#392]
hqq.tv hqq.watch
you script block p2p function on this players, becourse they use websocket to connection with signal server. Delete please this domains from your script else we will block users with adblock

**Comment by hoshsadiq** [comment]
Sorry for the late reply. Please give us an example page.

**Comment by Vladislavik** [comment]
https://netu.tv/view_page.php?pid=4

**Comment by hoshsadiq** [comment]
The video on that page works fine with only this list enabled
