### ISSUE TITLE
nocoin hosts.txt file do not support ipv6

### ISSUE THREAD

**Issue by bicobus** [hoshsadiq/adblock-nocoin-list#393]
Moving forward, the Internet will see the adoption of more and more ipv6 ready systems. More over, most web hosts already supports ipv6. As such, the hosts.txt file do not give adequate protection against mining.

**Comment by hoshsadiq** [comment]
This is correct. I've been thinking of dropping the hosts file from here to be honest. It's not been updated in a while. You're better off going to https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html as his list is much more up to date.
