### ISSUE TITLE
Request to unblock my mp3 files

### ISSUE THREAD

**Issue by paulrosen** [hoshsadiq/adblock-nocoin-list#394]
### Website with example

You can see an example of the files being blocked by going to https://abcjs.net and clicking the "play" triangle on the audio control.

The files being blocked have the form:

https://paulrosen.github.io/midi-js-soundfonts/FluidR3_GM/$INSTRUMENT-mp3/$NOTE.mp3

If I understand the blocking list, all github.io files are blocked from XmlHttpRequest, so I don't think there is any renaming I could do that would help.

**Comment by smed79** [comment]
Hi, 

@hoshsadiq for a while, I have not been faced with any mining activity using github.io so i removed it.

also removed from "Liste FR" https://hg.adblockplus.org/listefr/rev/281b0f3c06e6
