### ISSUE TITLE
mellivora.trade and mellivora.pro blocks web sockets

### ISSUE THREAD

**Issue by sibero** [hoshsadiq/adblock-nocoin-list#396]
The rule blocks the operation of web sockets on our site https://mellivora.trade and https://mellivora.pro . Please add our site to the exceptions. We have a legitimate service with tools for trading on the stock exchange

NoCoin Filter List. This rule
/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)(\.)?\/(.*)/$third-party,websocket,domain=~file.pizza|~instant.io|~myinterview.com|~webtorrent.io

**Comment by smed79** [comment]
Please, provide an example pages where we can test the issue.

**Comment by sibero** [comment]
URL: https://app.mellivora.pro/trades/bots
USER: demo
PASS: demodemo

Error in web console:
WebSocket connection to 'wss://api.mellivora.trade/ws/bot/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6InNpYmVybyIsImV4cCI6MTU3NjYxNjAwOCwiZW1haWwiOiJkcnVzaG9wQGdtYWlsLmNvbSJ9.13rswBroq-18sWttHFTDnpO-GBq5nPGfbinyved8FSM' failed: Unknown reason

**Comment by sibero** [comment]
> Please, provide an example pages where we can test the issue.
please, include the site in the exclusion list

**Comment by smed79** [comment]
- https://github.com/hoshsadiq/adblock-nocoin-list/commit/e1319df715c9560ef8d824c20c1b612688af7005
- https://github.com/easylist/easylist/pull/4526
- https://hg.adblockplus.org/listefr/rev/fa0f66c04679
