### ISSUE TITLE
Block Cloud Miner

### ISSUE THREAD

**Issue by arvindch** [hoshsadiq/adblock-nocoin-list#397]
### Website with example

[tpbay.xyz](https://www.tpbay.xyz)

### Domain causing the CPU spike

From viewing their source on this [link](https://www.tpbay.xyz/?load=/recent), they appear to be using:

https://cloud-miner.eu/tkefrep/tkefrepp.js?tkefrep=bs?nosaj=faster.moneroocean

This seems customized to my locale/device/whatever looking at the hashed URL. Presumably, blocking `https://cloud-miner` would be the solution here.

### Screenshot

Apologies, but didn't want to reproduce this - it spiked my 8-core MBP to 1000% CPU usage and I'm not interested in that happening again.

**Comment by arvindch** [comment]
Thanks! 😄

**Comment by smed79** [comment]
You're welcome!

thanks for the report.
