### ISSUE TITLE
fonts.gstatic.com

### ISSUE THREAD

**Issue by rfgamaral** [hoshsadiq/adblock-nocoin-list#398]
I believe this list is blocking `fonts.gstatic.com` which provides custom web fonts for many of Google's websites, like Google Calendar.

This wasn't happening a few weeks ago and based on the commit history I believe the issue lies with this change: https://github.com/hoshsadiq/adblock-nocoin-list/commit/0f0b3bb90f2d6d4fee2cb7c1d85564bd607b9c23

Can you please look into this?

**Comment by hoshsadiq** [comment]
I've tried multiple sites with just this list loaded, and they all load fonts.gstatic.com fine (including Google Calendar). Do you have an example link of where this is blocked?

**Comment by rfgamaral** [comment]
I'm sorry, after triple-checking everything, this list was not at fault. Apologize for the confusion. Keep up the good work 👍
