### ISSUE TITLE
Make Browser Extension for Maxthon. 

### ISSUE THREAD

**Issue by DrRazon** [hoshsadiq/adblock-nocoin-list#399]
### Website with example

<< Example of pages that are mining >>

### Domain causing the CPU spike

<< The domain that's actually doing the mining >>
<< For example coin-hive, coin-have etc (not the actual page) >>
<< You may leave this empty >>

### Screenshot

<< Optionally a screenshot of high CPU usage in task/activity manager >>

**Comment by hoshsadiq** [comment]
Creating this as an extension is beyond the scope of this project. I suggest you find an adblocker for Maxthon and add this list to it. I'm not familiar with Maxthon so I couldn't recommend an extension but after a quick search it seems Maxthon has Adblock Plus built in. It might be worth looking to see if you can add it to that.
