### ISSUE TITLE
Request: host file variant

### ISSUE THREAD

**Issue by kmleow** [hoshsadiq/adblock-nocoin-list#4]
Could you please make a hosts file version of this blocklist so that it can used in routers?

**Comment by hoshsadiq** [comment]
Has been added in pr #6

**Comment by kmleow** [comment]
Thank you @hoshsadiq 

I have updated my blog post to include information on how to use this host file in dnsmasq on OpenWRT.

https://www.leowkahman.com/2017/07/23/block-ads-with-openwrt-dnsmasq/
