### ISSUE TITLE
WebSockets Blocking for Third-Party Domains

### ISSUE THREAD

**Issue by meefik** [hoshsadiq/adblock-nocoin-list#402]
Hello!

This filter blocks WebSocket connections on legal sites that use WS connections to third-party domains, e.g. ".online".

Our service use WS connection to `*.proctoring.online` that was blocked on the page `https://proctoredu.com/demo`:

`wss://demo.proctoring.online/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0dWRlbnRfMTU4MzkzMjUxMDI1NSIsInJvbGUiOiJzdHVkZW50IiwicHJvdmlkZXIiOiJwbGFpbiIsInJvb20iOiIxNTgzOTMyNTEwMjU1IiwiaWF0IjoxNTgzOTQ1MzY0LCJleHAiOjE1ODQwMzE3NjR9.gL8fwBMjCeVpfEALzWS375z8QaKtFTPpAK4kL_FMi5o&EIO=3&transport=websocket`

Problem with this line number:
https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt#L559

`/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|online|ovh|party|pro|pw|racing|review|rocks|science|sh|site|space|stream|tk|top|trade|webcam|win|xyz|zone)(\.)?\/(.*)/$third-party,websocket,domain=~file.pizza|~instant.io|~mellivora.pro|~mellivora.trade|~myinterview.com|~webtorrent.io`

Please fix it.

**Comment by meefik** [comment]
Thanks for this fix! But it does not work :( Your need to add domain `proctoring.online` instead `proctoredu.com` and `proctoredu.ru`.

**Comment by smed79** [comment]
Hi;

The WS request is not blocked on the page example you have provided.

![proctoredu](https://user-images.githubusercontent.com/1873139/76685861-3a807700-6617-11ea-9bb9-e9247388a468.png)

Please, describe exactly how to reproduce the issue.

**Comment by meefik** [comment]
Yes, it work for `proctoredu.com` and `proctoredu.ru`. But our clients use many another domains with the SDK that loading from `*.proctoring.online`...

**Comment by smed79** [comment]
Please provide a real testable online sites.

**Comment by meefik** [comment]
`proctoredu.com` and `proctoredu.ru` is a real sites that  connecting to `*.proctoring.online` through WebSocket. But there are many other client domains that use the WebSocket connection to `*.proctoring.online`.

**Comment by meefik** [comment]
Please exclude these domains:

- proctoring.online
- startexam.com
- stepik.org

https://github.com/hoshsadiq/adblock-nocoin-list/blob/b4c55098baa3fbd1b64bc438af89e7426eddcf74/nocoin.txt#L561

```diff
--- /^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|online|ovh|party|pro|pw|racing|review|rocks|science|sh|site|space|stream|tk|top|trade|webcam|win|xyz|zone)(\.)?\/(.*)/$third-party,websocket,domain=~file.pizza|~instant.io|~mellivora.pro|~mellivora.trade|~myinterview.com|~proctoredu.com|~proctoredu.ru|~webtorrent.io
+++ /^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|online|ovh|party|pro|pw|racing|review|rocks|science|sh|site|space|stream|tk|top|trade|webcam|win|xyz|zone)(\.)?\/(.*)/$third-party,websocket,domain=~file.pizza|~instant.io|~mellivora.pro|~mellivora.trade|~myinterview.com|~proctoredu.com|~proctoredu.ru|~proctoring.online|~startexam.com|~stepik.org|~webtorrent.io
```
