### ISSUE TITLE
add lokbit.com

### ISSUE THREAD

**Issue by kikz0rsk** [hoshsadiq/adblock-nocoin-list#403]
### Website with example

https://lokbit.com/en

### Domain causing the CPU spike

Cannot provide, my browser gets irresponsive

### Screenshot
![image](https://user-images.githubusercontent.com/20465221/79672523-30800400-81d3-11ea-8a4a-92a2d9df2b13.png)

**Comment by ZeroDot1** [comment]
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues/58

**Comment by kikz0rsk** [comment]
Closing this issue as stated [here](https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues/58#note_326808324)
