### ISSUE TITLE
Websocket Connection Blocked (How to whitelist a site?)

### ISSUE THREAD

**Issue by AidanNelson** [hoshsadiq/adblock-nocoin-list#408]
I am a web developer and have created a website which connects to a back end server using websockets.   The websocket connections are being blocked by this filterlist.  

**Could you let me know how  to whitelist this site?**

You can see the site here:  https://spaceship.media.mit.edu/  With the _Cryptocurrency (Bitcoin) Mining Protection List_ filter list enabled in AdBlock on Chrome, connections to the back end server at seibackend.xyz are being blocked:

<img width="717" alt="Screen Shot 2020-08-28 at 1 43 09 PM" src="https://user-images.githubusercontent.com/6486359/91599617-8e1c1e00-e934-11ea-86eb-26fe5dd3dfbd.png">

**Comment by jdw1023** [comment]
I am guessing that it is due to this line. https://github.com/hoshsadiq/adblock-nocoin-list/blob/3fa618d31ecb1fb81c4c443d0aab3a553c758749/nocoin.txt#L561

**Comment by hoshsadiq** [comment]
I'm not seeing any websockets from that URL with no adblock enabled.

**Comment by AidanNelson** [comment]
Hmm @hoshsadiq there is a websocket connection to seibackend.xyz, but it isn't enabled until you go through the 'onboarding' (i.e. click through the first two modals).

Let me know if/ how I can submit a PR to fix this.  I am hosting a virtual event in the space on Friday, so would love to fix this without requiring people to pause AdBlock.

Thanks!

**Comment by AidanNelson** [comment]
Fantastic.  Thank you @hoshsadiq !

**Comment by AidanNelson** [comment]
@hoshsadiq Can I also request that you whitelist [yorbbackend.xyz](https://yorbbackend.xyz)?
