### ISSUE TITLE
uBlock list

### ISSUE THREAD

**Issue by 737simpilot** [hoshsadiq/adblock-nocoin-list#409]
Hi. I see that there is a coin list for Adblock, but I don't see the uBlock list being updated in a long time. Not sure if the uBlock list already blocks what Adblock does.

**Comment by hoshsadiq** [comment]
You should be importing the adblock version. [uBlock will automatically include the uBlock list](https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt#L653) too. The list simply contains some uBlock specific syntax.
