### ISSUE TITLE
Add Bitcoin Bootstrap to the list.

### ISSUE THREAD

**Issue by tg12** [hoshsadiq/adblock-nocoin-list#416]
Add Bitcoin Bootstrap to the list.

seed.bitcoin.sipa.be
dnsseed.bluematt.me
dnsseed.bitcoin.dashjr.org
seed.bitcoinstats.com
seed.bitcoin.jonasschnelli.ch
seed.btc.petertodd.org
seed.bitcoin.sprovoost.nl
dnsseed.emzy.de
seed.bitcoin.wiz.biz

**Comment by hoshsadiq** [comment]
I've revert this. This list is not for blocking legitimate uses of Bitcon or other cryptocurrency systems. This list is about blocking domains that mine cryptocurrencies in your browser without the user's consent. Bitcoin bootstrap addresses do not fall under that category. I should have been paying more attention when I added them, I was a little tired so wasn't thinking straight.
