### ISSUE TITLE
polkadot.js.org

### ISSUE THREAD

**Issue by RasmonT** [hoshsadiq/adblock-nocoin-list#419]
Hello there,

NoCoin list filter is blocking realis network exlorer on polkadot.js.org

Blocked site:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.realis.network%2F#/explorer

I'll believe there is no any kind of mining going on, as other explorers are working and shows correctly with this filter on.

Screenshot of blockation

![image](https://user-images.githubusercontent.com/35234558/116830061-f4360080-aba7-11eb-978d-d76e70ad7460.png)
![image](https://user-images.githubusercontent.com/35234558/116830079-0e6fde80-aba8-11eb-9bfb-7f9a36519b25.png)

Hopefully this is the right place to report the issue.

Best regards,

RasmonT.

**Comment by smed79** [comment]
Hello,

Fixed > https://github.com/hoshsadiq/adblock-nocoin-list/commit/299bd0bdd28b96f7c345baddb5e76debca0cd54a & https://github.com/easylist/listefr/commit/099cf1af2b88e3bed9af49e9c83104113d1a6b68
