### ISSUE TITLE
list of browser miners

### ISSUE THREAD

**Issue by callmenemo491** [hoshsadiq/adblock-nocoin-list#42]
this article mentions the other browser miners, that we can extract and create the necessary pull requests:
https://www.bleepingcomputer.com/news/security/the-internet-is-rife-with-in-browser-miners-and-its-getting-worse-each-day/

**Comment by SMed79** [comment]
Which one is not blocked?

If you want to help provide an example sites using mining script which are not blocked.

**Comment by maprezentalok** [comment]
hello I found a mining script. script is here: http://huiwiw.hit.gemius.pl/xgemius.js that is called by embedded script on another site (dmdamedia.hu)

<![CDATA[//><!]]>
  | </script>

**Comment by hoshsadiq** [comment]
@maprezentalok I don't see any mining happening on those two websites, could you please elaborate a bit?

**Comment by SMed79** [comment]
`gemius.pl` Is a tracker server [blocked](https://github.com/easylist/easylist/search?utf8=✓&q="||gemius.pl^%24third-party") in easyprivacy.

**Comment by hoshsadiq** [comment]
@callmenemo491 any updates? If not, I will close this issue.
