### ISSUE TITLE
Unblock siteapi.idkfa.online

### ISSUE THREAD

**Issue by SukhikhN** [hoshsadiq/adblock-nocoin-list#423]
Hello!

We use siteapi.idkfa.online domain as backend and we have several websites on other domains that connect to it via wesockets (and more to come). Now websockets on siteapi.idkfa.online is blocked by the TLD rule: https://github.com/hoshsadiq/adblock-nocoin-list/blob/3f1f82779d3095c0eb089014e42e82b7ff40927a/nocoin.txt#L579

Can siteapi.idkfa.online itself be added to the exception list, so we will not need to add each new website which needs to connect to it? I see exception domain list in that rule, but as far as I understand these domains are the ones from which connection established, not the backend domains.

**Comment by SukhikhN** [comment]
Learned how to add exceptions. Could this be merged please?

**Comment by smed79** [comment]
Hello,

Provide examples website !!

**Comment by SukhikhN** [comment]
https://hp.7riches.club/fifi - our main production domain.

**Comment by hoshsadiq** [comment]
What exactly doesn't work? Seems to work for me.
