### ISSUE TITLE
rpc.realis.network

### ISSUE THREAD

**Issue by barmanabarmana** [hoshsadiq/adblock-nocoin-list#427]
Hi
I am trying to connect to custom api realis.network in localhost but it fails with 1006:abnormal closure
![image](https://user-images.githubusercontent.com/87117376/133383722-3ab9c98b-1b80-4b14-9a82-bc06d8bb84cd.png)

I know that the adBlock is the issue,if i turn it off everything works fine
Could you please remove it from the auto-ban filter
Thank you

api: wss://rpc.realis.network

**Comment by smed79** [comment]
Hi, 

whitelist in your adblocker

* Adbkock Plus > https://help.eyeo.com/adblockplus/add-a-website-to-the-whitelist
* AdBlock > https://help.getadblock.com/support/solutions/articles/6000055743
