### ISSUE TITLE
kab.sh

### ISSUE THREAD

**Issue by amnonbb** [hoshsadiq/adblock-nocoin-list#428]
Hi.
Can you please add to white list *.kab.sh
We got many backends using 3d level subdomain.

Thanks

**Comment by smed79** [comment]
Hi, 

provide an example of page(s) that are mining using `*.kab.sh`

**Comment by amnonbb** [comment]
It's not mining. I ask for adding in **white** list.
Our client got blocking WebSocket connection by default.

![block1](https://user-images.githubusercontent.com/4086676/134797458-4dcd0699-cb16-46b5-9ca9-5dfdac1b6c7c.png)

![block2](https://user-images.githubusercontent.com/4086676/134797468-1643b12b-2751-4ce9-9f4a-39106239e339.png)

 And explain to everyone how to add in white list manually it's big problem.
