### ISSUE TITLE
hqq.tv, hqq.watch (p2p / websocket)

### ISSUE THREAD

**Issue by slthelion** [hoshsadiq/adblock-nocoin-list#429]
### Website with example
Exemple tab - Server 1
* `https://topfilmenoi.net/epoca-de-gheata-ploaie-de-meteoriti-2016-online-subtitrat.html`

Exemple tab - Netu.tv
* `http://www.filmeserialeonline.org/episodul/pilot-23/`

### Domain causing the CPU spike

This domain is used for video delivery, not  for mining. Because of this, videos on many sites are not working.
They use p2p system via WebRTC protocol to deliver video chunks between each other peers.
There is no spike on CPU.

**Comment by cronlabspl** [comment]
Video delivery, seriously? Are you able to prove it? Because many CPU spikes are caused by fake video players, and miners are hiding behind video-players

**Comment by smed79** [comment]
Rejected.

**Comment by Vladislavik** [comment]
same here, player use p2p, just open page with your nocoin module, and will be error, because plpayer use p2p via websockets and cant connect with this module active
[https://topfilmenoi.net/epoca-de-gheata-ploaie-de-meteoriti-2016-online-subtitrat.html](Server1)

**Comment by Vladislavik** [comment]
> Video delivery, seriously? Are you able to prove it? Because many CPU spikes are caused by fake video players, and miners are hiding behind video-players

Before asking this just mopen example page and check F12 source if you doenot know how p2p work

**Comment by hoshsadiq** [comment]
@Vladislavik please add it to your local allow list.
