### ISSUE TITLE
[False positive] *.zkopru.network

### ISSUE THREAD

**Issue by JChanceHud** [hoshsadiq/adblock-nocoin-list#435]
Hi, I'm a developer on the Zkopru team building an Ethereum layer 2 blockchain. Our TLD is `zkopru.network` and we access some services at `*.zkopru.network`. This is being blocked by the TLD filter in the current version of the blocklist.

Could you whitelist the `*.zkopru.network` subdomains? Thanks

**Comment by hoshsadiq** [comment]
Please add it to your local whitelist.

**Comment by hoshsadiq** [comment]
Please add it to your local allow list.

**Comment by JChanceHud** [comment]
We're running a public beta. It seems unreasonable to ask users to modify or disable their adblock just to use our service.

**Comment by hoshsadiq** [comment]
Do you have an example page?

**Comment by JChanceHud** [comment]
The homepage is [here](https://zkopru.network).

The wallet itself is [here](https://zkopru.network/wallet). To use the wallet you need metamask installed and switched to the Goerli network.

**Comment by cronlabspl** [comment]
> Please add it to your local allow list.

whats the point of this?
