### ISSUE TITLE
About inwemo.com

### ISSUE THREAD

**Issue by Vetm** [hoshsadiq/adblock-nocoin-list#44]
I'm the Co-Founder and main developer of Inwemo. It's really sad for us to see that we ended up on your list. We understand that in-browser mining hasn't had the best start with miners secretly running in the background without the user knowing. With Inwemo we wanted to try a different approach. We have a mandatory opt-in for every website that uses Inwemo to ensure that our miner only runs when the user explicitly allows it – **the mining will never happen without the user's consent**.

With your current solution our consent will be shown to the user but the mining wont start even if he hits the "I agree"-button.

Our goal is to offer a user-friendly and non-intrusive alternative to ads. We do everything we can to be as transparent and fair as possible to everyone.

We'd be very grateful for any suggestions for changes on our product that might get us removed from your list. If there's nothing we can do, we'll of course accept your decision and won't try stuff like domain rotation etc.

We're happy to hear your thoughts!

**Comment by ZeroDot1** [comment]
Hi @Vetm  I moved your service to the optional list.
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by hoshsadiq** [comment]
Hi @Vetm, thanks for this. It's good to see sensible businesses who are fair to the users. I had one issue with your implementation, and that's that I had no easy way of disabling the mining after opting in. Can you confirm that it is possible to opt out afterwards? This is not the first time and I'm happy to remove it providing it's fair to the website users.

**Comment by SMed79** [comment]
@hoshsadiq The role of **[NoCoin adblock list](https://github.com/hoshsadiq/adblock-nocoin-list#nocoin-adblock-list)** is to completely block browser-based crypto mining or **ONLY** someone of them?

> I'm happy to remove it

I do not agree especially when it is about a third party...

**Comment by Vetm** [comment]
@hoshsadiq Currently the user's decision is saved for two weeks. After that the opt-in will be shown again. We know that this isn't the best solution but from a webmasters perspective showing it every session wouldn't really be acceptable. We'll soon be implementing a message that pops up every session after the user has made his decision with an option to opt-out. In the meantime users can use our browser extension to have full control over Inwemo: https://inwemo.com/choice/

@ZeroDot1 Thank you very much! We appreciate that.

@SMed79 I get your point but do you think it is necessary to block them if the user has full control over it happening?

**Comment by hoshsadiq** [comment]
@SMed79 to me it is to block any non-sensible administrator's miners that hijack user CPU (i.e. always mining or opt-in but switched on by default, or in this case, opt-in but not easy to opt-out). If it's an opt-in feature, and you can at any time disable the mining (as goodolddownloads had in #36). That is providing this happens on all sites.

But you do raise a good question, how do we validate that third party websites that host a modified version of inwemo's code such that it's always opt-in. With that said, I'm inclined to agree with @SMed79 regarding third-party filters.

@Vetm I already read those things on your website. I don't think it is necessary to require a user to install an extension just to have to opt-out of a service. If I can opt-in without the extension, I should be able to opt-out without the extension, and without being required to wait a really long time. As a web developer, I know that this is non-intuitive. Please have a look at issue #36. To me they are implementing browser mining the way it should be done. Opt-in, and easy to opt-out of. Anything less is not acceptable.

**Comment by ZeroDot1** [comment]
@SMed79 The CoinBlockerLists are meant to block mining completely, it should help administrators to prevent mining in their networks.
I know it doesn't make sense to block everything, but there is the optional list.

**Comment by SMed79** [comment]
@ZeroDot1 What you had to do is to keep all mining domains blocked in the **default list** (for admin networks) and create a **second list** without the clean pool sites (for normal user).

**Comment by ZeroDot1** [comment]
@SMed79 feel free to contribute to the project.
https://github.com/ZeroDot1/CoinBlockerLists/issues/7

**Comment by SMed79** [comment]
@ZeroDot1 Are you sure about what you have add in [this commit](https://github.com/ZeroDot1/CoinBlockerLists/commit/3e58cdd408aed2ca05684089ad09ae80b2b5fdb4)? 
These are **popads** adservers not related to crypto mining !!

- https://forums.lanik.us/viewtopic.php?f=62&t=32538
- https://github.com/easylist/easylist/commit/2cf7ff38faac88f3d83e72d32e09511d1cdf0c4b

**Comment by ZeroDot1** [comment]
@SMed79 The new lists are ready, I hope it's better for you now:)
https://github.com/ZeroDot1/CoinBlockerLists/issues/7
https://github.com/ZeroDot1/CoinBlockerLists/issues/9

**Comment by hoshsadiq** [comment]
I will close this. @Vetm Please feel free to either raise a new issue once the above concerns have been address.
