### ISSUE TITLE
Doubts about nimiq domains

### ISSUE THREAD

**Issue by niwot** [hoshsadiq/adblock-nocoin-list#442]
Hi, 
today I have seen in my `nextdns.io` registry, the following list of domains, some blocked and some not. I have not entered any weird websites, I was looking for pictures of engineering stuff, in google images, for work issues. I don't have the history from my browser, and can't see from which particular link these domains were called from.

I understand that all the domains could have to do with cryptojacking because all those domains have been called from some "normal" website that I have entered (I have not entered any nimiq domain that I remember). But I have hardly any information on these issues, and I pass here the information, in case it would be useful.

I see that the domains `nimiq.community`; `nimiq.icemining.ca`; `nimiq.surf`; `seed.nimiq.jp`; `seed.nimiqchina.com` are not blocked by this list, neither is `node.nimiq.watch`, and perhaps you can evaluate if there are indications or reasons to include them.

I have read the thread https://github.com/hoshsadiq/adblock-nocoin-list/issues/343 ; but I think this is different and you should analyze it in case there is something relevant. If the information is useless, my apologies.

This is the list of domains that I have detected browsing today (all domains are registered in my profile of nextnds.io within 10 minutes, I think it is some browser tab that I left open that time):

- **domain status reasons**
```
nimiq.community
nimiq.icemining.ca
nimiq.surf
node.nimiq.watch blocked cryptojacking
seed.nimiq.jp
seed.nimiqchina.com
seed.nimiqpool.com blocked cryptojacking,blocklist:oisd
seed-1.nimiq.com blocked cryptojacking,blocklist:oisd
seed-10.nimiq.network blocked cryptojacking,blocklist:oisd
seed-11.nimiq.network blocked cryptojacking,blocklist:oisd
seed-12.nimiq.network blocked cryptojacking,blocklist:oisd
seed-13.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-14.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-15.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-16.nimiq.com blocked cryptojacking,blocklist:oisd
seed-17.nimiq.com blocked cryptojacking,blocklist:oisd
seed-18.nimiq.com blocked cryptojacking,blocklist:oisd
seed-19.nimiq.com blocked cryptojacking,blocklist:oisd
seed-2.nimiq.com blocked cryptojacking,blocklist:oisd
seed-20.nimiq.com blocked cryptojacking,blocklist:oisd
seed-3.nimiq.com blocked cryptojacking,blocklist:oisd
seed-4.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-5.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-6.nimiq-network.com blocked cryptojacking,blocklist:oisd
seed-7.nimiq.network blocked cryptojacking,blocklist:oisd
seed-8.nimiq.network blocked cryptojacking,blocklist:oisd
seed-9.nimiq.network blocked cryptojacking,blocklist:oisd
```

**Comment by smed79** [comment]
Hi,
difficult to investigate, be sure to provide example sites to help us.

checked & I added https://github.com/hoshsadiq/adblock-nocoin-list/commit/113136423cb95f8c16762af9b996230f5712a495

`nimiq.community` **not added**, unable to find proof of cryptojacking.


Thank you.

**Comment by niwot** [comment]
.
