### ISSUE TITLE
monerominer.rocks

### ISSUE THREAD

**Issue by ZeroDot1** [hoshsadiq/adblock-nocoin-list#45]
http://monerominer.rocks/about-monero-miner/

**Comment by SMed79** [comment]
Embed where?

**Comment by hoshsadiq** [comment]
They seem to be using coin-hive, so no need to add any more rules

**Comment by ZeroDot1** [comment]
http://monerominer.rocks/scripts/miner.js

**Comment by hoshsadiq** [comment]
The script doesn't need to be blocked. As long as coinhive is blocked (which it is), mining won't work.
