### ISSUE TITLE
4everland.store

### ISSUE THREAD

**Issue by summercms** [hoshsadiq/adblock-nocoin-list#454]
### Website with example

I ran the injected malware link in virus total and has 4 detections, link found here:
https://www.virustotal.com/gui/url/49b77640b2b32eeea465794a09c1b7a364e736aa2b825973b772dceee398d7e4/

The hackers created a url from that domain called:

```
sui-img.4everland.store/
```

I'm going to guess they have created several URL's from that domain, e.g.

```
sui-img.4everland.store/
bitcoin-img.4everland.store/
ethereum-img.4everland.store/
```

etc.

### Domain to Block

Can we block the following domain:

```
4everland.store
```

### Screenshot

Here's a screenshot of Bitdefender going crazy with the crypto DEX with this injected file:

![image](https://github.com/hoshsadiq/adblock-nocoin-list/assets/57409060/d484e48d-052a-4eda-b3f3-fdcdb8d22648)

### Other Info

I was looking at a new crypto DEX on the new SUI Blockchain, the project website is:

```
httpx://app.cetus.zone/
```

Have sent them a message asking them to clean up their DEX website, as **their pool page is injecting this crypto malware from a third-party source.**

**Comment by hoshsadiq** [comment]
Again, I don't see any mining activity on the website.
