### ISSUE TITLE
sui-pepe.xyz

### ISSUE THREAD

**Issue by summercms** [hoshsadiq/adblock-nocoin-list#455]
### Website with example

I went to the following url:

httpx://sui.bluemove.net/

It connected to a Malware website called:

httpx://sui-pepe.xyz

Proof:

https://virustotal.com/gui/url/8de59d5b0bced2132dd9f07048751a58494f97486d0d6bde64507ad51a502a80

### Domain to Block

```
sui-pepe.xyz
```

### Screenshot

From Bitdefender

![image](https://github.com/hoshsadiq/adblock-nocoin-list/assets/57409060/9d17960b-5c98-4dd1-bb48-6740eb1bbfb5)

### More info

Have contacted the BlueMove SUI Blockchain NFT Marketplace to ask them to clean up their website.

**Comment by hoshsadiq** [comment]
I don't see any crypto mining activity on the page in your posted. Can you link an example page where it is currently mining using the given pages?
