### ISSUE TITLE
Non-cryptominers (Google Analytics, Facebook, Twitter) blocked due to regexp rule

### ISSUE THREAD

**Issue by lmoretto** [hoshsadiq/adblock-nocoin-list#464]
Hello,

The following regexp rule causes famous non-cryptominer services like `www.google-analytics.com`, `connect.facebook.net` and `platform.twitter.com` to be blocked:https://github.com/hoshsadiq/adblock-nocoin-list/blob/e514ecfb30b58e9de3246a3099dfaba52fb0bc7f/nocoin.txt#L458

The issue has been reproduced on some specific domains that are targeted by this rule, in particular:
- `deltabit.co`
- `www.filmovix.net`
- `www.firstonetv.live`

**Comment by smed79** [comment]
`connect.facebook.net` & `platform.twitter.com` has been excluded [\_here\_ ](https://github.com/hoshsadiq/adblock-nocoin-list/commit/c336045eae31121d1143f39f5d0f45188bc26c07#diff-6da5b5f15c6cf1da8ac5bf66ef43b4900810eb31bb5f9cdf60d4db3783c25dd9R313).

No exception will be add for `www.google-analytics.com`

**Comment by lmoretto** [comment]
Hi @smed79, thanks for applying these changes. May I ask why you decided not to add an exception for `www.google-analytics.com`?

**Comment by smed79** [comment]
If a specific extreme blocking measure is applied for a site, no exception or exclusion will be added for a tracking site.
