### ISSUE TITLE
Help me check the nocoint list at ABP 4.4

### ISSUE THREAD

**Issue by HoangHaiDang02** [hoshsadiq/adblock-nocoin-list#466]
### Problem

I can't import the filter rules into ABP at version 4.4. Maybe rule did blocked by 

`(https?|wss?):\\/\\/([0-9a-z\\-]+\\.)?([0-9a-z\\-]+\\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|online|ovh|party|pro|pw|racing|review|rocks|science|site|space(?!(\\[/socket](tg://bot_command?command=socket)\\[/websocket](tg://bot_command?command=websocket)\\?vsn\\=))|stream|tk|top|trade|webcam|win|xyz|zone)(\\.)?\\/(.*)`

Help me check it

### Screenshot

![image](https://github.com/user-attachments/assets/27531376-9cac-4664-ae73-5ba75e9013ad)

**Comment by smed79** [comment]
It is related to the limitation of google manifest v3

Read
https://blog.adblockplus.org/blog/how-adblock-plus-is-getting-ready-for-manifest-v3
https://blog.adblockplus.org/releases/adblock-plus-40-for-chrome-firefox-microsoft-edge-and-opera

the latest old version of Adblock Plus for Chrome compatible Manifest v2, can be downloaded from

https://downloads.adblockplus.org/adblockpluschrome-3.25.1.zip

To sideload the old Adblock Plus v3.25.1 for Chrome check below link 

https://help.adblockplus.org/hc/en-us/articles/29256324064147-Sideload-Adblock-Plus-for-Chrome
