### ISSUE TITLE
pfBlockerNG and other Perimeter Solutions

### ISSUE THREAD

**Issue by bytesizedalex** [hoshsadiq/adblock-nocoin-list#47]
Hi,

As well as recommending software be installed on client devices it might be worth providing information on perimeter solutions - e.g pfSense can be enhanced with pfBlockerNG to protect all devices on a network with block lists.

**Comment by mrmcmuffinz** [comment]
👍

**Comment by hoshsadiq** [comment]
I'm not sure I follow. There is no recommended software to section. These are required for using this. I'm happy to have a separate section about pfSense with pfBlockerNG. However, you will need to raise a PR as I've never used pfSense and never even heard of pfBlockerNG.

**Comment by mrmcmuffinz** [comment]
When I first read this issue I interpreted it by assuming the request was to provide support for pfBlockerNG in pfsense via host files but that being said reading the issue again I'm not sure if I follow it myself. I have configured pfBlockerNG to use the hosts file option in this repository via the DNSBL Feeds and importing the hosts file. That being said after inspecting the HOSTS option it looks to me like it's incorrect. Shouldn't we be redirecting to localhost instead of 0.0.0.0 for hosts list?

**Comment by bytesizedalex** [comment]
Hi both,

Firstly apologies - I left the comment after a long shift and didn't provide sufficient detail to fully explain what I meant. I came across your repository by chance and didn't want to forget to post. What I should have said was in your readme/homepage for the repo you list a number of solutions which can be used and I felt it might be worth adding pfSense and pfBlockerNG or other firewall solutions as a perimeter solution.

pfBlockerNG is a plugin for the pfSense firewall which allows one to ingest IPv4/v6 and DNS names which are then filtered out on your edge firewall. pfBNG does this via the DNS resolver, it simply resolves all undesirable addresses to a dummy IP and pixel image resulting in them not loading. I went looking and found this Reddit post which includes a link to your list, as such I believe support is already there and this was simply a suggestion to mention these products in the readme to help get more people using them.

**Comment by hoshsadiq** [comment]
@mrmcmuffinz I'm not quite sure. I don't use the hosts file for blocking. I have always been under the impression 0.0.0.0 was the one but having looked online a little bit, it seems people can use either. Going further, it looks like 0.0.0.0 means localhost as much as 127.0.0.1 means localhost. So I don't think it matters.

@bytesizedalex Sure. I've updated the readme a little bit. If you could have a look and let me know if this is adequate.

**Comment by bytesizedalex** [comment]
Yep, OK with me - it's nice to have the edge protection as it means all devices are covered without needing to install and configure on all of them. That goes for mobile/tablet devices too :)

**Comment by hoshsadiq** [comment]
Great! :) Closing this now!

**Comment by SMed79** [comment]
@mrmcmuffinz 
> After inspecting the HOSTS option it looks to me like it's incorrect. Shouldn't we be redirecting to localhost instead of 0.0.0.0 for hosts list?

Read: [RECOMMENDATION FOR USING 0.0.0.0 instead of 127.0.0.1](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist#recommendation-for-using0000-instead-of-127001)
