### ISSUE TITLE
browsermine.com/browsermine.js

### ISSUE THREAD

**Issue by mastad0n** [hoshsadiq/adblock-nocoin-list#53]
http://browsermine.com/browsermine.js

Webmasters get their code as such:

http://browsermine.com/browsermine.js?u=123456

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/60

**Comment by hoshsadiq** [comment]
This is just coinhive, this small JS will execute, which will then try to inject coinhive, which will not happen due to the coinhive filter.

**Comment by mastad0n** [comment]
Thank you @hoshsadiq
