### ISSUE TITLE
http://ad-miner.com/ missing

### ISSUE THREAD

**Issue by giantpune** [hoshsadiq/adblock-nocoin-list#56]
I was just comparing your list to some other similar lists.  From spot checking, I found at least one that is not on your list.  I'm not sure if there are others.

http://ad-miner.com/
https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt

**Comment by im3or** [comment]
Many missing, not just this. 
But that is an extension, all the url's have to be checked correctly.

**Comment by hoshsadiq** [comment]
Thanks! I am on holiday at the moment, I will add any that are missing as soon as I can.

**Comment by hoshsadiq** [comment]
Of course PRs are also welcome!

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/57

**Comment by hoshsadiq** [comment]
I've added adminer. I will leave this open and I will look at the rest of at a later date.

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/commit/22cde4a074b448c4989a3570ff50ae11410e33bb

**Comment by im3or** [comment]
Thanks & keep up the good work.

**Comment by hoshsadiq** [comment]
I've looked through that list, and have added the additional domains not on this filter list providing I could see miner scripts. I will be closing this now. Thanks for the report.
