### ISSUE TITLE
coinhiveproxy.com

### ISSUE THREAD

**Issue by GUiHKX** [hoshsadiq/adblock-nocoin-list#59]
Found on this website: https://csgoconfigs.com/

Adding `||coinhiveproxy.com^$third-party` worked for me, although I'm not sure if that's the proper filter.

Thanks in advance.

**Comment by hoshsadiq** [comment]
I've merged #60 and #61, though that domain doesn't seem to resolve nor does csgoconfigs show any miner lists.
