### ISSUE TITLE
openkatalog.com

### ISSUE THREAD

**Issue by mat41997** [hoshsadiq/adblock-nocoin-list#64]
![2017-12-08 20_50_24-menedzer zadan](https://user-images.githubusercontent.com/5884000/33782756-36afef14-dc5a-11e7-9971-e47717b35eea.png)

![2017-12-08 20_49_57-openkatalog com ogladaj filmy i seriale bez limitu](https://user-images.githubusercontent.com/5884000/33782762-3ab3a5c4-dc5a-11e7-8ce3-548322f6ed64.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4804

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by SMed79** [comment]
```
||openkatalog.com/static/openkatalog/cpuproject.php
```

**Comment by MajkiIT** [comment]
@SMed79 
I think that better will be `||openkatalog.com/static/$subdocument` , because yesterday was `||openkatalog.com/static/anyemotions/*$subdocument` . 2 Days ago was ||openkatalog.com/*.js*proxy=wss://$script etc.

**Comment by ZeroDot1** [comment]
This site uses Cinhive. 
![bildschirmfoto_2017-12-09_17-04-40](https://user-images.githubusercontent.com/28985171/33797146-12c74a58-dd03-11e7-93ee-f84c03c0aa0e.png)

**Comment by hoshsadiq** [comment]
Yes! It's just using coinhive, which is already blocked.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/600045/33797214-fd67c7a2-dcfb-11e7-9197-d323d6371663.png">

**Comment by hoshsadiq** [comment]
Reopening. as @MajkiIT said, this is similar to #62. I couldn't reproduce it on openkatalog.com, however, I've added a new filter as part of #62 so if someone can test it and report back. Otherwise I'll add @SMed79's filter.

**Comment by MajkiIT** [comment]
@hoshsadiq Thanks

**Comment by SMed79** [comment]
@okiehsch fyi.

**Comment by MajkiIT** [comment]
@SMed79 @hoshsadiq today is `https://openkatalog.com/newstatic/cpuproject.html`

**Comment by hoshsadiq** [comment]
Thanks. I've added the same filter as @SMed79 added to uAsset. Let me know if it continues
