### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by mat41997** [hoshsadiq/adblock-nocoin-list#65]
![2017-12-09 05_51_28-menedzer zadan](https://user-images.githubusercontent.com/5884000/33792607-10cfcc56-dca5-11e7-8fbc-d3008ec12cfa.png)

![2017-12-09 05_47_26-dragon ball super episode 118 - watch anime online english subbed](https://user-images.githubusercontent.com/5884000/33792591-b06d67d8-dca4-11e7-8fc8-2f1622906d78.png)
`https://otakustream.tv/anime/dragon-ball-super/episode-118/`

to reproduct
+ play the wideo
+ wait at 5minutes

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by mat41997** [comment]
i don't know
![2017-12-10 01_07_10-3-gatsu no lion season 2 episode 9 - watch anime online english subbed](https://user-images.githubusercontent.com/5884000/33800732-a7f9b44c-dd46-11e7-964e-d7013528cc4a.png)

**Comment by ryanbr** [comment]
Website issues, unrelated.

**Comment by okiehsch** [comment]
The site crashes my chrome-tab if the miner successfully initiates, so I don't think it is a website issue,
if I block `rapidvideo.com/J5xj_2.js` or kill the script via `rapidvideo.com##script:inject(abort-on-property-write.js, decodeURIComponent)` the website and the video plays fine on my end.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/21512543bef26a27d2817fd7cce3cb33acc6ceb9

Though if they intentionally break their own site by revolving the script, it should be left alone imo.

**Comment by mat41997** [comment]
@ryanbr nope.. if they intentionally break their own site by revolving the script. i think, it should be reported here
https://github.com/jspenguin2017/uBlockProtector/issues

this is a anti-adblock mechanizm

**Comment by okiehsch** [comment]
@mat41997 your chrome-tab will crash because of the mining script, which will run with or without an adblocker, so how is this an anti-adblock mechanism?

**Comment by mat41997** [comment]
@okiehsch ohh.. sorry, I did not check. you're right

**Comment by hoshsadiq** [comment]
I've added @okiehsch as well I've deobfuscated the JS file, and figured out some of the domains they're using. All blocked now.

**Comment by ZeroDot1** [comment]
@hoshsadiq Thank you, I have added all domains to the CoinBlockerLists.
https://github.com/ZeroDot1/CoinBlockerLists/issues/73

**Comment by ryanbr** [comment]
`https://www.rapidvideo.com/800d7b76ac4e7736cc7a9e9d92cb180e.js`

As expected it changed, blanket block done. Don't have time for their shit. 

https://github.com/easylist/easylist/commit/21f466a7622bd26a36b7cbb56634dd695fcc5959

And if they intend to embed any CPU abuse script into the whitelisted scripts, I'll remove each whitelist regardless of the importance.
