### ISSUE TITLE
dead domains

### ISSUE THREAD

**Issue by MajkiIT** [hoshsadiq/adblock-nocoin-list#66]
```
Host azvjudwr.info
Host jroqvbvw.info
Host jyhfuqoh.info
Host kdowqlpt.info
Host xbasfbno.info
```

**Comment by hoshsadiq** [comment]
They are still registered. Because there's so few, I think it's fine to keep it in there until after it's unregistered. Just in case they revive them. I will put them in a separate section

**Comment by SMed79** [comment]
@MajkiIT Read me again [easylist#509](https://github.com/easylist/easylist/issues/509#issuecomment-326666420)... No ping response does not mean the domains are dead.

![http://i.imgur.com/VRn99I0.png](http://i.imgur.com/VRn99I0.png)
