### ISSUE TITLE
Blocks do not work on wstream.video

### ISSUE THREAD

**Issue by thezar86** [hoshsadiq/adblock-nocoin-list#71]
Hi, yesterday i used for the first time this useful list importing it in adblock on macos. It was working very well: the full cpu usage decreased to a normal video rendering during streaming.
Now it is not working. The cpu goes to 100% again.
There is something i can do to block the cryptonight script again?
Thank you for this very useful work.

**Comment by ehatle** [comment]
Step 1. Figure out what sites are causing issues.
Step 2. Document your findings here.
Step 3. Figure out what script is causing the decreased performance.
Step 4. Add the script to your local list
Step 5. Check if it worked. If it did document your findings here. If it didnt go back to step 3.
Good luck!

**Comment by thezar86** [comment]
1. I found out that sometimes it works but sometimes not, i'm trying to understand if this may be a safari related issue.
2. http://wstream.video/hwu2pkkhhot7 for example gives me the full cpu usage.
3. How can i find the script using cpu?
Thank you!

**Comment by SMed79** [comment]
All the third party scripts are [already blocked](https://hg.adblockplus.org/easylist/rev/4f20a7772fd9) by easylist on `wstream.video`
However, the mining script is `http://noblock.pro/lib/noblock.js` ([#pull/73](https://github.com/hoshsadiq/adblock-nocoin-list/pull/73/files))

**Comment by hoshsadiq** [comment]
Added. Pushing soon.
