### ISSUE TITLE
update

### ISSUE THREAD

**Issue by axo1** [hoshsadiq/adblock-nocoin-list#72]
hi, nice work with this list. Can you update with this filter?
wty46.com/js/noblock.js

thanks!

**Comment by hoshsadiq** [comment]
I will look at this over the weekend and will add it to the list.

**Comment by SMed79** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/pull/73/commits/0006d3ba22576113fff2c29d20312ec94a1194ff

**Comment by hoshsadiq** [comment]
Weird. I tried merging that several times through and GitHub but it kept saying it's not merged. Glad it did merge in the end! Closing this now!
