### ISSUE TITLE
Missing crypto.csgocpu.com site

### ISSUE THREAD

**Issue by soldadozka** [hoshsadiq/adblock-nocoin-list#74]
Hello!
I found this little snippet in a webpage's code:
![firefox_2017-12-16_23-36-35](https://user-images.githubusercontent.com/34610906/34074967-0f642dba-e2ba-11e7-923c-3d84650d7753.png)

https://crypto.csgocpu.com/cryptocpu.js

**Comment by SMed79** [comment]
> I found this little snippet in a webpage's code

Next time provide an example page !!

`https://lewd.ninja/`

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/87

**Comment by SMed79** [comment]
@ZeroDot1 why add 19 domain/subdomains if blocking "crypto.csgocpu.com" is enough?!!

**Comment by ZeroDot1** [comment]
@SMed79 It is important to add all domains if possible, as the lists also serve as a source of information.

**Comment by hoshsadiq** [comment]
@SMed79 Thanks, I will add it over the weekend.
@ZeroDot1 Blocking the highest domain is to block all the subdomains with it.

**Comment by hoshsadiq** [comment]
Added `||crypto.csgocpu.com^third-party`. Will push soon.
