### ISSUE TITLE
Additional filters

### ISSUE THREAD

**Issue by qthinh4996** [hoshsadiq/adblock-nocoin-list#76]
||cryptoloot.pro^
||bjorksta.men^

**Comment by hoshsadiq** [comment]
I've adding cryptoloot (will push soon), bjorksta seems to be just an nginx page. Do you have an example of it being used?

**Comment by SMed79** [comment]
> Do you have an example of it being used?

on **vidoza.net** embed videos https://pastebin.com/raw/cENNJp1P
```
http://bjorksta.men/miniTipForksNew.min.js
http://bjorksta.men/miniTipForks.min.js
https://bjorksta.men/am.rel.js?v=20122017
```
check also
```
https://vidoza.net/js/plugins/miniTip/jquery.miniTip.min.js
```

**Comment by hoshsadiq** [comment]
Just had a look, seems they're just using coinhive. The links examples you mentioned don't bring up my CPU. See https://bjorksta.men/miniTipForksNew.min.js, and search for `WEBSOCKET_SHARDS`. Anyway, just in case, I've added borksta.men as a third party filter.
