### ISSUE TITLE
vidoza.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#77]
![2017-12-18 15_30_44-menedzer zadan](https://user-images.githubusercontent.com/5884000/34110949-7f9a5934-e408-11e7-9439-0e2c67e278c6.png)

![2017-12-18 15_31_05-https___vidoza net_embed-8h0p111k6mtm html](https://user-images.githubusercontent.com/5884000/34110957-8446641e-e408-11e7-9f63-cc126b0c7f34.png)
`https://vidoza.net/embed-8h0p111k6mtm.html`

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.14
Nano Defender 13.3
Chrome 63.0.3239.108

**Comment by SMed79** [comment]
test these filters
```
@@||ajax.googleapis.com/ajax/libs/$script,domain=vidoza.net
@@||cdnjs.cloudflare.com/ajax/libs/$script,domain=vidoza.net
@@||vidoza.net/js/ads.js$script,domain=vidoza.net
@@||vidoza.net/js/pop.js$script,domain=vidoza.net
|http://$script,third-party,domain=vidoza.net
|https://$script,third-party,domain=vidoza.net
||vidoza.net/js/sop/
$popup,domain=vidoza.net
```
@ryanbr fyi.

**Comment by hoshsadiq** [comment]
Not seeing anything, is it worth adding this?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1f9bd0652f35ae294b960406214308ddeb2c7186

Should cover it.

**Comment by hoshsadiq** [comment]
Still can't see anything with adblock disabled completely (see screenshot). Anyway, I've added @ryanbr filters in the commit (just those related to vidoza.net). Thanks
<img width="897" alt="image" src="https://user-images.githubusercontent.com/600045/34342993-025261a8-e9ba-11e7-86de-8d50a54d02cd.png">
