### ISSUE TITLE
I found new javascript code for crypto coins in powvideo.

### ISSUE THREAD

**Issue by SrCroqueta** [hoshsadiq/adblock-nocoin-list#80]
I blocked it with minerBlock and it stopped running, now my cpu it's fine.

This is the URL: https://powvideo.net/js/jquery.cookie.js

Just paste like this in minerBlock:  

`*://*.powvideo.net/js/jquery.cookie*`

 and should work.

**[P.S: _minerBlock_ is an Google's add-ons].**

**Comment by SrCroqueta** [comment]
It works, but you can not start the film, so I investigated and I found this in the code:

![901d4a75ae412303bbd705b9edf64f7d](https://user-images.githubusercontent.com/32432079/34342660-016f2a12-e9b7-11e7-8b0d-4a89866d2900.png)

How you can see in the last line, it use **coin nebula**. Now my question, how can I block this without affect to the video player?

**Comment by hoshsadiq** [comment]
Thanks! Do you have an example page were I can see it in action?

**Comment by SrCroqueta** [comment]
I used HDFull.tv and selected powvideo for see a film, but try with this one: **https://powvideo.net/9ks9ofsu616y** I can block it, but I can't see the film because the play button disappears when blocking the link that I put in the first post. I'm trying find the correct, but I can't. It use **coin nebula**, and I have blocked **coinnebula.com** but didn't work. Maybe you can help me.

Thanks for the reply.

**Comment by SrCroqueta** [comment]
Okay, I see something interesting, **powvideo not just use coinnebula**, it use **different crypto mining**. My add-ons detected **it using now coin-hive**, so it was blocked and my cpu was fine, so I think **it use different crypto mining radomly**. For now I don't have problems with coin-hive, but **I still have the same problem with coinnebula.**

_(Sorry if my english is a little bit bad, I'm from Spain :') )_

**Comment by hoshsadiq** [comment]
Added 
```
$websocket,domain=powvideo.net
||1q2w3.me^third-party
```

**Comment by SrCroqueta** [comment]
Okay!, thanks for that help.
