### ISSUE TITLE
1Blocker issue

### ISSUE THREAD

**Issue by UniverseXXX** [hoshsadiq/adblock-nocoin-list#83]
Hi!
Thanks a lot for this.
I've got an error when adding it to the 1Blocker on macOS: "The operation couldn't be completed. (WKErrorDomain error 2)". The same occurs on iOS.

Would you be able to update 1Blocker file in line with the recent hosts' updates?

Many thanks.

**Comment by hoshsadiq** [comment]
I'm not too sure, I don't use 1Blocker. @Patronics might be able to help.

**Comment by hoshsadiq** [comment]
Merged #89 which should fix this. Let us know if it doesn't.
