### ISSUE TITLE
Need blocking for Gearslutz (studio/audio website)

### ISSUE THREAD

**Issue by gavinsitterly** [hoshsadiq/adblock-nocoin-list#84]
updated the uBlock filter, still get heavy CPU usage (mining I presume) when visiting https://www.gearslutz.com

**Comment by hoshsadiq** [comment]
Can't seem to see anything suspicious on the main page. Do you have a specific page that's causing it?

**Comment by gavinsitterly** [comment]
Maybe they removed it, doesn't seem to be there for me either now when I go through the site.

**Comment by gavinsitterly** [comment]
Actually found a page that is reproducing it again. Went back to some old links from my history and they do not have the same issue. Maybe it's just a certain ad that gets rotated on the site? Anyway as of right now this link is producing the high CPU usage.

https://www.gearslutz.com/board/geekslutz-forum/785432-capacitors-use-recapping.html

**Comment by SMed79** [comment]
source ==> **minr.pw**

```
||minr.pw^$third-party
||cndhit.xyz^$third-party
||g-content.bid^$third-party
||statistic.date^$third-party
||g-content.bid^$third-party
||cdnfile.xyz^$third-party
||statistic.date^$third-party
||clod.pw^$third-party
||static-cnt.bid^$third-party
||dle-news.pw^$third-party
||jquery-uim.download^$third-party
||hallaert.online^$third-party
||nut.cc^$third-party
||flu.cc^$third-party
||usa.cc^$third-party
||igg.biz^$third-party
```
```
0.0.0.0 minr.pw
0.0.0.0 cndhit.xyz
0.0.0.0 g-content.bid
0.0.0.0 statistic.date
0.0.0.0 ad.g-content.bid
0.0.0.0 cdnfile.xyz
0.0.0.0 cnt.statistic.date
0.0.0.0 web.clod.pw
0.0.0.0 static-net.nut.cc
0.0.0.0 static-02.flu.cc
0.0.0.0 cdn.static-cnt.bid
0.0.0.0 web.dle-news.pw
0.0.0.0 cdn.jquery-uim.download
```

**Comment by gavinsitterly** [comment]
Added those to "my filters" and seems to be blocking...assume that's all I need to do? Thanks!
