### ISSUE TITLE
Add this to hosts file

### ISSUE THREAD

**Issue by Vigneshsam** [hoshsadiq/adblock-nocoin-list#85]
miner.cryptobara.com , found it when opening firefox dev edition with some extensions, avast always popup with this message saying it blocked js-miner(trj) on miner.cryptobara.com, even on default page. Tried to find which extension is secretly mining,unfortunately unable to find. Switched to chrome.

**Comment by SMed79** [comment]
> when opening firefox dev edition with some extensions

Do you have some examples?

@hoshsadiq find `http://miner.cryptobara.com/client/deepMiner.js` here `http://biciklo.xyz/`

```
/deepMiner.js
||cryptobara.com^$third-party
```
```
0.0.0.0 miner.cryptobara.com
```

**Comment by ZeroDot1** [comment]
Don't forget:
```bash
http://digger.cryptobara.com/client/deepMiner.js
http://digger.cryptobara.com/client/worker.js
LIB_URL: "http://digger.cryptobara.com/client/lib/",
WEBSOCKET_SHARDS: [["ws://digger.cryptobara.com:7777/"]],
CAPTCHA_URL: "http://digger.cryptobara.com/client/captcha/",
MINER_URL: "http://digger.cryptobara.com/client/media/miner.html"
```

**Comment by Asciicodeplus** [comment]
I found this pop up hiding minimized and my cpu at 100%:

http://www.reservedoffers.club/s/?utm_source=admaven&utm_campaign=admaven-v2-shopping-topgeos-d-windowsMacosx_top-popunder-WL&utm_medium=64582&utm_content=salefiles.com&utm_term=676105&cpv=0.00046

seems to be calling a script to mine ethereum for the host of the add, in this case salefiles.com, an online file storage

**Comment by SMed79** [comment]
> I found this pop up

@Asciicodeplus which is the website that open this popup?

**Comment by Asciicodeplus** [comment]
@SMed79 

http://salefiles.com/

**Comment by hoshsadiq** [comment]
Added both. Thanks @mapx-
@Asciicodeplus if you can, in the future, open new tickets for new filters :)
