### ISSUE TITLE
web miner

### ISSUE THREAD

**Issue by Asciicodeplus** [hoshsadiq/adblock-nocoin-list#87]
this website:

http://skyback.ru/

seems to be executing this script:

https://biberukalap.com/7632112235a3bb2.2.n.2.1.js

that then creates this background process:

blob:http://skyback.ru/2f931319-3c39-458c-8101-9fbe6aa30462

the last alphanumeric string is always random (2f931319-3c39-458c-8101-9fbe6aa30462), but if you open the link directly the mining script is plainly visible

**Comment by SMed79** [comment]
```
||biberukalap.com^
||gridiogrid.com^
```
```
0.0.0.0 biberukalap.com
0.0.0.0 gridiogrid.com
```

**Comment by hoshsadiq** [comment]
Thanks, added. Will push in a minute.
