### ISSUE TITLE
Does not seem to work on https://thepiratebay.cr

### ISSUE THREAD

**Issue by gombosg** [hoshsadiq/adblock-nocoin-list#90]
### Website with example

https://thepiratebay.cr

### Domain causing the CPU spike

Own domain unfortunately. :(

Script name is random GUID-based, like
`blob:https://thepiratebay.cr/2ed497c6-ca74-48a6-9c33-c130695afbc6`

Please take a look. I'm using Opera 50 and NoCoin does work when tested on other websites.

**Comment by mapx-** [comment]
`?proxy=wss://mine.torrent.pw$script`

**Comment by crssi** [comment]
`?proxy=$script` breaks video at https://www.wrc.com/en/video/player/?videoId=337067

The rule is referenced at https://github.com/uBlockOrigin/uAssets/blob/bdb6f42d30539e913d7fddadbe325238899d7ce8/filters/resource-abuse.txt#L30-L31

**Comment by mapx-** [comment]
removed

**Comment by crssi** [comment]
Huh... this was prompt 😄 
Thank you for your work, cheers
