### ISSUE TITLE
Mining code on bablace.com

### ISSUE THREAD

**Issue by jacekoleksy** [hoshsadiq/adblock-nocoin-list#92]
### Website with example

kinokrad.co 

### Domain causing the CPU spike

bablace.com

### Screenshot

<img width="469" alt="screen shot 2018-01-10 at 10 29 47" src="https://user-images.githubusercontent.com/35292764/34765224-3df95a2a-f5f1-11e7-9088-839706551672.png">

**Comment by hoshsadiq** [comment]
Thank you, it's been merged.
