### ISSUE TITLE
estream.to

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#94]
![2018-01-13 00_07_48-menedzer zadan](https://user-images.githubusercontent.com/5884000/34898909-d3407d88-f7f5-11e7-8fdf-2ab6a739fc53.png)
`https://estream.to/embed-xpi8wzu4j1ad.html`

my filters
easylist + polish filters + nocoin

Nano Adblocker 1.0.0.26
Nano Defender 13.19
Chrome 63.0.3239.132

**Comment by mapx-** [comment]
`||analytics.blue^`

**Comment by SMed79** [comment]
@KonoromiHimaries add thse filters https://forums.lanik.us/viewtopic.php?p=130417#p130417

@ryanbr fyi.

**Comment by hoshsadiq** [comment]
Will be added momentarily. Thanks!

**Comment by ryanbr** [comment]
Seems to be bug in uBo, not understanding webrtc. when I added the filter

**Comment by mapx-** [comment]
for uBo use
`example.om##script:inject(nowebrtc.js)`

**Comment by ryanbr** [comment]
Tho ubo shouldn't just not apply the filter because it didn't understand one switch.

**Comment by mapx-** [comment]
or you could start an uBo-specific list, see
`Sub-filter lists` from:
https://github.com/gorhill/uBlock/releases
