### ISSUE TITLE
intactoffers.club

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#95]
![2018-01-13 06_01_27-menedzer zadan](https://user-images.githubusercontent.com/5884000/34902965-3a1a60f6-f827-11e7-9f8a-1b73b66e3121.png)
`http://www.intactoffers.club/s/?utm_source=popads&utm_campaign=popads-v2-intactoffers-tier3-d-w10-WL&utm_medium=General%2FArts%2FEntertainment&utm_content=10&utm_term=2111264&cpv=0.000278`

my filters
easylist + polish filters + nocoin

Nano Adblocker 1.0.0.26
Nano Defender 13.19
Chrome 63.0.3239.132

**Comment by mapx-** [comment]
`||intactoffers.club^$csp=child-src 'none';frame-src *;worker-src 'none';`

How did you land on the page above ?

**Comment by KonoromiHimaries** [comment]
@mapx- i clicked the streamango player
`https://fili.tv/serial/templariusze/s01e01/youd-know-what-to-do/27795`

**Comment by mapx-** [comment]
```
DUE TO RECEIVED MPAA (Motion Picture Association of America)
NOTICE OF COPYRIGHT INFRINGEMENT, THE SCOPE OF SERVICES
OF OUR WEBSITE HAS BEEN PERMANENTLY LIMITED TO THE
EXTENT THAT FULLY COMPLIES WITH INTERNATIONAL LAW.

PLEASE USE THIS RESOURCE TO FIND ANY FILM:
http://www.findanyfilm.com/
```

**Comment by hoshsadiq** [comment]
Thanks @mapx- I'll add it momentarily.
