### ISSUE TITLE
alltube.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [hoshsadiq/adblock-nocoin-list#97]
![2018-01-14 03_25_02-menedzer zadan](https://user-images.githubusercontent.com/5884000/34912182-888f077e-f8da-11e7-9aca-fc24f34690f1.png)

my filters
easylist + polskie filtry + nocoin

Nano Adblocker 1.0.0.26
Nano Defender 13.19
Chrome 63.0.3239.132

**Comment by SMed79** [comment]
```
.webcam^$domain=alltube.tv
||64uq73u7ug.webcam^
```
```
0.0.0.0 64uq73u7ug.webcam
```

**Comment by KonoromiHimaries** [comment]
@SMed79 still not work
![2018-01-14 04_24_05-menedzer zadan](https://user-images.githubusercontent.com/5884000/34912478-d484c67a-f8e2-11e7-9862-831bd68115bb.png)

**Comment by mapx-** [comment]
```
/bootstrap.wasm$xmlhttprequest
||smectapop12.pl^
```

**Comment by MajkiIT** [comment]
@KonoromiHimaries update polish filters and check.
